src/extension/notebook.ts
Provide links to github issues and discord.
=> In case something goes wrong try to be helpful

examples/deploy/README.md
Working through some examples and improving them along the way.
=> Template for deeper integration

examples/deploy/README.md, src/client/components/vercel.ts, src/constants.ts, src/extension/executors/shell.ts, src/extension/kernel.ts, src/extension/utils.ts, src/types.ts
As part of a refactor we could fill in gaps running queries against the API.
=> Exclusively use CLI

src/extension/extension.ts
=> Pass in right directory when calling `runme` CLI

examples/k8s/README.md
Added interactivity and cleanup
=> Minimal edits

.github/workflows/release.yml, examples/README.md, src/extension/notebook.ts, src/types.ts
Pick up on new wasm lib interface to provide more robust parsing.
=> New wasm interface (parser)

package.json, src/extension/commands/index.ts, src/extension/extension.ts, src/extension/provider/background.ts, tests/extension/commands/index.test.ts, tests/extension/extension.test.ts, tests/extension/provider/background.test.ts
covers #62  and https://github.com/stateful/vscode-runme/pull/48
=> reimplemented stop task btn ux

.github/workflows/release.yml, .github/workflows/test.yml, .yarnrc, src/extension/commands/index.ts, src/extension/executors/shell.ts, src/extension/executors/task.ts, src/extension/provider/background.ts, src/extension/provider/cli.ts, src/extension/serializer.ts, src/extension/utils.ts, src/types.ts, tests/e2e/specs/basic.e2e.ts, tests/e2e/wdio.conf.ts, tests/extension/commands/index.test.ts, tests/extension/kernel.test.ts, tests/extension/provider/background.test.ts
Slightly refactored to better leverage types plus unit & e2e tests.
Relates to https://github.com/stateful/runme/issues/83. Tests will pass once PR (https://github.com/stateful/runme/pull/84) is merged.
=> Bring back CLI button (and respective metadata)

__mocks__/vscode.ts, package.json, src/extension/commands/index.ts, src/extension/extension.ts, tests/extension/commands/index.test.ts, tests/extension/extension.test.ts
=> Add create new Runme notebook menu item

package.json, src/extension/serializer.ts, src/extension/utils.ts, tests/extension/serializer.test.ts, tests/extension/utilts.test.ts
=> Allow user to lift save restriction

package.json, walkthroughs/0-intro.md, walkthroughs/1-annotations.md
A little walkthrough addition to help get people started on Runme. This could be a potential reason we might want to move our docs into this repo.
Demo:
=> Add Walkthrough

README.md, package.json, src/extension/commands/index.ts, src/extension/serializer.ts, tests/extension/serializer.test.ts, walkthroughs/0-intro.md, walkthroughs/1-annotations.md
=> Copy changes

src/extension/kernel.ts, tests/extension/kernel.test.ts
=> Prompt user for every cell when executing 'Run All'

src/extension/serializer.ts, src/types.ts
Dependent on https://github.com/stateful/runme/pull/92.
=> Make sure we leave frontmatter untouched

src/extension/commands/index.ts, tests/extension/commands/index.test.ts
=> Set filename when running Runme through CLI

src/extension/kernel.ts, tests/extension/kernel.test.ts
=> Don't show confirmation for notebooks with just one cell

examples/k8s/package-lock.json, examples/vercel/package-lock.json, src/extension/executors/task.ts
Subtle, yet impactful bug, when the task type is set to `runme` it will pick up on some of the semantic defined in `package.json` which in effect won't allow the `npx next dev` & `open http...` in `examples/vercel/README.md` to run because it thinks they are "the same" task. Will prompt to "restart" or "stop" instead which is wrong.
=> Fix small bugs

src/extension/provider/runmeTask.ts, vitest.conf.ts
Fixes https://github.com/stateful/vscode-runme/issues/121. Thanks for reporting!
=> Handle file not found error

package.json, src/client/components/annotations.ts, src/extension/provider/annotations.ts, src/extension/provider/cli.ts
I still would like the "?" at some point where we can describe *why* now that the UI show the "what". I'd be comfortable shipping as is though.
Will squash upon merge.
=> Copy changes and slight UI adjustment

package.json, src/client/components/annotations.ts, src/extension/provider/annotations.ts, src/extension/provider/cli.ts
Introducing UI tweaks for annotations, includes:
- placeholders instead of labels for textinput
- Remove grid component for composing the layout, it adapts to the screen width and behaves well under zoom in/out
TODO: Include an explanatory "?" for each element
Solves [https://github.com/stateful/vscode-runme/issues/131](url)
Light Mode
Dark Mode
=> Annotations UI Improvements

src/extension/provider/launcher.ts, vitest.conf.ts
Fixes [https://github.com/stateful/vscode-runme/issues/136](https://github.com/stateful/vscode-runme/issues/136)
=> Fix displaying absolute paths

.github/dependabot.yml, .github/workflows/update.yml
This patch adds two files (`dependabot.yml` and `update.yml`) that allows us to have dependencies automatically updated (once every week), if our pipeline passes. I've been using this approach in WebdriverIO now very successfully and thought we could adapt this too.
=> Auto update project dependencies

package.json, src/extension/extension.ts, src/extension/provider/launcher.ts, tests/extension/extension.test.ts, tests/extension/provider/launcher.test.ts
=> Implement collapse/expand all buttons to explorer

src/extension/handler/uri.ts, tests/extension/handler/uri.test.ts
We want to know how many people use the launcher to setup a project with Runme.
=> Add teletemtry for uri handler

src/extension/handler/uri.ts, tests/extension/handler/uri.test.ts
=> Sanitize urls before using them in terminal

__mocks__/vscode.ts, package-lock.json, package.json, src/extension/handler/uri.ts, src/extension/handler/utils.ts, tests/e2e/specs/launcher.e2e.ts, tests/extension/handler/uri.test.ts, tests/extension/handler/utils.test.ts
This broke with the last release. I am working on e2e tests but feel free to review
=> Fix url parsing for git@ urls

__mocks__/vscode.ts, src/extension/extension.ts, src/extension/kernel.ts, src/extension/serializer.ts, src/extension/utils.ts, tests/extension/serializer.test.ts
Fixes #188. Please review @degrammer or @mxsdev whoever gets to it sooner.
=> Code cells always require session UUIDs

src/extension/cli/server.ts, src/extension/extension.ts
Will work with the respective release candidate from https://github.com/stateful/runme/releases/tag/v0.6.0-rc.0
Makes https://github.com/stateful/vscode-runme/pull/209 work.
=> Still needs more refactoring

package.json, src/extension/extension.ts, src/extension/kernel.ts
For flexible development and testing until this is fully finalized closer to release.
=> Break out bringing up GRPC server from consuming a service

examples/fresh/README.md, src/extension/executors/deno/deploy.ts, src/extension/executors/runme.ts, src/extension/executors/runner.ts, src/extension/executors/shell.ts, src/extension/executors/utils.ts, src/extension/executors/vercel/auth.ts, src/extension/executors/vercel/deploy.ts, src/extension/provider/annotations.ts, src/extension/utils.ts, tests/extension/executors/utils.test.ts, tests/extension/provider/annotations.test.ts
Fixes https://github.com/stateful/vscode-runme/issues/233.
=> Until underlying bug's fixed

package.json, src/extension/kernel.ts
=> Flip GRPC server & parser to be default "active"

src/extension/executors/deno.ts, src/extension/executors/deno/deploy.ts, src/extension/executors/index.ts, src/extension/executors/runner.ts, src/extension/executors/shell.ts, src/extension/executors/vercel.ts, src/extension/kernel.ts, src/extension/runner.ts, tests/extension/__snapshots__/utils.test.ts.snap, tests/extension/kernel.test.ts
This PR is currently working. Vercel works great, but deno will not work until the following are fixed:
- ~~#268 (deno deploy script in example is multiline)~~
- [runme/#166](https://github.com/stateful/runme/issues/166) (`deployctl deploy` does not work in interactive mode
I tested suppressing the deno output in non-interactive mode, and everything worked fine. So, once those are fixed, this PR should work for deno.
=> Runner service deno/vercel integration

src/client/components/annotations.ts
Small fix to provide better form validation while the user types
=> Provide better feedback on Form validation

src/extension/handler/uri.ts, src/extension/handler/utils.ts, tests/extension/__snapshots__/utils.test.ts.snap, tests/extension/handler/uri.test.ts, tests/extension/handler/utils.test.ts
=> Make run with Runme easier by not requiring a full git setup

__mocks__/vscode.ts, src/extension/extension.ts, src/extension/provider/launcher.ts, tests/extension/provider/launcher.test.ts
Implements #158
~missing work:~
~- add unit tests~
=> Implement file watcher for tree viewer

src/extension/executors/runner.ts
Removed unneeded dispose call which was terminating the background program's execution prematurely.
My bad!
=> Fix background tasks with gRPC runner

src/extension/server/runmeServer.ts
Temporary measure until #326 is merged. CI will fail until this is merged
=> Pass insecure flag to runme server

package.json, src/client/components/terminal.ts, src/extension/executors/runner.ts, src/extension/notebookTerminal.ts, src/types.ts, src/utils/configuration.ts
Fixes https://github.com/stateful/vscode-runme/issues/334
=> Add Notebook terminal settings

package.json, src/extension/kernel.ts
If you'd please do me the review honors @mxsdev.
=> Flip the default switch for Runner

src/extension/handler/utils.ts
Fixes problem where file stat fails after project checkout in `waitForProjectCheckout`
Basically just retries, waiting 100ms between attempts, until it can stat the file. If the file isn't found it returns false rather than erroring, since errors aren't handled by the uri handler anyway.
=> Retry file stat in wait for project checkout

src/client/components/terminal.ts, src/utils/ansi.ts
Adds copy button to notebook terminal
=> Add copy button to notebook terminal

package.json, src/extension/executors/utils.ts, src/extension/extension.ts, src/extension/kernel.ts, src/extension/survey.ts, src/extension/utils.ts, src/extension/win.ts, src/utils/configuration.ts, tests/extension/extension.test.ts, tests/extension/server/runmeServer.test.ts, vitest.conf.ts
Respectfully ask Windows users to share what default shell they are using so we can prioritize better.
=> Windows shell survey

package-lock.json, package.json, src/client/components/terminal.ts, src/constants.ts, src/extension/kernel.ts, src/types.ts
Prevent copy & paste for opening Notebook Terminal links. Allow click to open
=> Add Notebook terminal weblinks support

src/extension/executors/runner.ts
Prints code on close in notebook terminal for background tasks. Improves UX
=> Print code on close in background tasks

src/extension/executors/runner.ts
=> Respect custom mime types in Notebook Terminal-enabled cells

.github/scripts/getLastStableRelease.js, CONTRIBUTING.md
The same's been working well for WASM.
Needed this to review a PR that requires a release candidate for @mxsdev.
=> Pre-releases for anything but main which is default

examples/vercel/README.md, src/extension/executors/runner.ts
The first commit in the PR is an observable-less solution whereas with the second commit applied, it will use rxjs.
=> Resolve jitter for streaming outputs

__mocks__/vscode.ts, package.json, src/extension/commands/index.ts, src/extension/extension.ts, src/extension/grpc/genericTypes.ts, src/extension/provider/codelens.ts, src/extension/provider/runmeTask.ts, src/types.ts, src/utils/configuration.ts, tests/extension/configuration.test.ts, tests/extension/extension.test.ts, tests/extension/runner.test.ts
Requires stateful/runme#218 to work properly
Still not done:
- ~~User setting to toggle CodeLens support~~
- ~~Only apply to markdown files~~
- ~~Unit tests~~
=> CodeLens support

examples/README.md, tests/e2e/pageobjects/cell.page.ts, tests/e2e/specs/basic.e2e.ts
I've written my suggestions to #405 as a PR
This properly integrates page objects and also fixes the issue of scrolling
@degrammer
=> e2e Test Improvements

src/extension/extension.ts, src/extension/provider/codelens.ts, src/extension/survey.ts, tests/extension/runner.test.ts
=> Survey Windows users in CodeLens Run 

src/client/components/outputItems.ts, src/client/components/terminal.ts, src/extension/commands/index.ts, tests/extension/commands/index.test.ts
=> Remove successful copy & stop task popups

package.json, src/extension/commands/index.ts, src/extension/extension.ts, src/extension/utils.ts, tests/extension/commands/index.test.ts, tests/extension/extension.test.ts, tests/extension/utils.test.ts
Introduces "Open with Runme" button for all markdown files in the explorer menu.
=> "Open with Runme" explorer context menu

__mocks__/vscode.ts, src/extension/commands/index.ts, src/extension/extension.ts, src/utils/configuration.ts, tests/extension/commands/index.test.ts, tests/extension/extension.test.ts
=> Add runme executable to PATH

package.json, src/extension/utils.ts, src/schema.ts, tests/extension/schema.test.ts, tests/extension/utils.test.ts
Part of #430 
Now schema defaults are set properly
=> Remove annotation override configuration

package.json, src/constants.ts, src/extension/extension.ts, src/extension/server/runmeServer.ts, src/extension/server/runmeServerError.ts, src/utils/configuration.ts, tests/extension/configuration.test.ts
=> Replace 'port' setting with 'custom address'

src/extension/grpc/serializerTypes.ts, src/types.ts
=> Use serializer types from grpc

src/extension/executors/runner.ts, src/extension/utils.ts, tests/extension/utils.test.ts
=> Use cell uuid for terminal identification

src/extension/provider/runmeTask.ts
=> Fix parse order in `runmeTask`

src/client/components/annotations.ts, src/constants.ts, src/extension/constants.ts, src/extension/executors/runner.ts, src/extension/executors/task.ts, src/extension/executors/utils.ts, src/extension/provider/runmeTask.ts, src/schema.ts, src/types.ts, tests/extension/executors/utils.test.ts, tests/extension/utils.test.ts
=> Add "promptEnv" setting to toggle prompting for environment vars

.github/workflows/release.yml
Updating deprecated GH Action https://github.com/marketplace/actions/gabrielbb-xvfb-action in favor of xvfb
=> replacing deprecated gabrielbb-xvfb-action

package-lock.json, package.json, src/extension/commands/index.ts, src/extension/extension.ts, src/extension/services/github.ts, src/extension/services/index.ts, src/extension/services/types.ts, tests/extension/extension.test.ts
This PR register a command to authenticate with GitHub (used for testing purposes) and a new GitHub service that provides access to GitHub API via Octokit.
The command was used to test a workflow dispatch event https://github.com/stateful/runme-canary/actions/runs/4928319668/jobs/8806523478
how to dispatch a workflow with the API:
1. Get a GitHub Access Token 
```
const session = await authentication.getSession('github', ['repo'], { createIfNone: true })
const githubService = new GitHubService(session.accessToken)
```
2.  Dispatch a workflow
```
await githubService.createWorkflowDispatch({
owner: 'stateful',
repo: 'runme-canary',
workflow_id: 'test-inputs.yml',
ref: 'main',
inputs: {
publishMarketplace: 'no',
publishOpenVSX: 'no',
releaseChannel: 'edge',
releaseType: 'patch', …
```
=> GitHub authentication

tests/e2e/specs/basic.e2e.ts
Works locally. Want to see if this passes CI. Open to other suggestions.
=> Match subset of words

.github/scripts/downloadAndExtract.js, .github/scripts/getLastStableRelease.js, CONTRIBUTING.md, package.json
=> Improvements on Windows setup

src/extension/executors/runner.ts
=> Fix show terminal for custom mimeType

package-lock.json, package.json, src/extension/executors/runner.ts, src/extension/provider/runmeTask.ts, src/extension/runner.ts
Solves #519
Requires stateful/runme#250 (proto changes needed for build)
=> Store last stdout in `$__`

.github/workflows/test.yml, package-lock.json, package.json
Let's simplify our CI setup and use our new task runner.
=> (chore): use new runme task runner in CI

src/extension/cell.ts, src/extension/kernel.ts, src/extension/provider/annotations.ts, src/extension/utils.ts, tests/extension/cell.test.ts, tests/extension/utils.test.ts
Should solve #497, though I don't have a repro unfortunately
TODO: tests
=> Prompt user to select default kernel

.github/workflows/test.yml
=> Remove explicit version in test CI

src/extension/executors/runner.ts, src/extension/executors/utils.ts, src/extension/provider/codelens.ts, src/extension/provider/runmeTask.ts, src/extension/runner.ts, src/extension/serializer.ts, src/types.ts, tests/extension/executors/utils.test.ts, tests/extension/runner.test.ts
Support custom shells with frontmatter
In the future we should have this as a configuration option as well. Lmk if you want to wrap that up with this pr @sourishkrout 
Depends on #544
=> Support custom shells w/ frontmatter

__mocks__/vscode.ts, package-lock.json, src/extension/executors/runner.ts, src/extension/executors/utils.ts, src/extension/provider/runmeTask.ts, src/extension/serializer.ts, src/schema.ts, tests/extension/executors/utils.test.ts
Support cwd in frontmatter, annotations. Implemented identically to as in stateful/runme#270
=> cwd support

package.json, src/extension/kernel.ts
=> Changed description

__mocks__/vscode.ts, package.json, src/extension/extension.ts, src/extension/survey.ts, src/extension/utils.ts, tests/extension/utils.test.ts
Please help us improve Runme.
PS: Retired the default shell survey.
=> Feedback survey

src/extension/executors/utils.ts, src/extension/serializer.ts, src/types.ts, tests/extension/executors/utils.test.ts, tests/extension/serializer.test.ts
Fixes stateful/runme#280
For me, the notebook fails to save in this PR; see #566 for more details.
=> Fix frontmatter parsing as `[object Object]`

src/client/components/configuration/annotations.ts
Changed the config typo #584 and "re-opening" the last pr #587
=> Fixing the mimeType description to 'output'

examples/README.md
=> (docs): Add example to demo interactive terminal tools

package.json, src/extension/kernel.ts, src/extension/survey.ts, tests/extension/extension.test.ts, tests/extension/kernel.test.ts, tests/extension/provider/annotations.test.ts
Until we get shebang support out the door.
=> Use survey infra for lang not supported notification

package.json, src/extension/extension.ts, src/extension/survey.ts, tests/extension/extension.test.ts
Repurpose what previously was meant to be an exit survey.
=> Provide "Send Feedback" button in Notebook UX

package.json, src/extension/commands/index.ts, src/utils/configuration.ts, tests/extension/commands/index.test.ts
Solves https://github.com/stateful/runme/issues/321 with a new setting.
=> Configurable option to split or toggle editor view action

package-lock.json, package.json
Resolves issues bumping xterm versions
Usurps #637, #597
=> bump xterm

src/client/components/terminal/index.ts, src/extension/kernel.ts, src/extension/messages/cloudApiRequest/saveCellExecution.ts, src/types.ts
Do we know the difference between "Save" and "Share", @degrammer? If so, can you push changes on top of this PR, please?
=> Follow established events convention

examples/README.md, src/client/components/configuration/annotations.ts, src/extension/runner.ts, tests/extension/runner.test.ts
Getting it ready for pre-release.
=> Shebang UX tweaks

src/utils/configuration.ts, tests/extension/configuration.test.ts
Easier remote dev for localhost.
=> Handle specific endpoint

src/client/components/terminal/index.ts, src/extension/__generated__/gql.ts, src/extension/__generated__/graphql.ts, src/extension/messages/cloudApiRequest/index.ts, src/extension/messages/cloudApiRequest/updateCellExecution.ts, src/gql/updateCellExecution.graphql, src/types.ts
Update cell privacy when sharing a cell execution
=> feat: update cell privacy when sharing

src/client/components/github/workflowViewer.ts
Fixes https://github.com/stateful/vscode-runme/issues/745
=> Fix gh action default value

tests/e2e/helpers/index.ts, tests/e2e/specs/basic.e2e.ts, tests/e2e/specs/codelense.e2e.ts, tests/e2e/wdio.conf.ts
fixes #727
Work in progress: testing in CI and debugging failures.
=> (testing): add e2e tests for codelense support

src/extension/commands/index.ts, src/extension/extension.ts, src/extension/provider/codelens.ts, src/extension/utils.ts, tests/e2e/helpers/index.ts, tests/e2e/specs/codelense.e2e.ts, tests/extension/runner.test.ts
As per the user's request, please see the issue below.
Solves https://github.com/stateful/runme/issues/296.
=> "Paste into terminal" as additional option in codelenses

package.json, walkthroughs/0-intro.md, walkthroughs/1-features.md, walkthroughs/2-annotations.md, walkthroughs/3-learn-more.md, walkthroughs/4-learn-more.md
Updated the content and also changed the order to the following:
__1. Intro:__
__2. Key Features:__
__3. Cell Configurations:__
__4. Learn More:__
fixes #762
=> (docs): update walkthrough

examples/shebang.md
Happy to add more but those are the most common installed languages that work out of the box.
=> (docs): add simple example for shebang support across some common languages

examples/test.md, src/extension/provider/runmeTask.ts, tests/e2e/specs/codelense.e2e.ts
=> (bugfix): don't prompt for env if set to false

tests/e2e/specs/codelense.e2e.ts, tests/e2e/specs/githubAction.e2e.ts, tests/e2e/wdio.conf.ts
While just retrying isn't the ideal solution, if it unblocks us for now it is worth moving forward with that as I don't see any consistent flakes yet.
=> (test): retries test files at least twice

.github/dependabot.yml, package-lock.json, package.json
After having internal discussions about this , let's stick with the version that is actually run within Electron.
Closes #793
=> Align @types/node with what is supported in Electron

package.json, src/client/components/terminal/index.ts, src/client/index.ts, src/extension/cell.ts, src/extension/commands/index.ts, src/extension/server/runmeServer.ts, src/types.ts, src/utils/configuration.ts, tests/extension/__snapshots__/configuration.test.ts.snap, tests/extension/commands/index.test.ts, tests/extension/configuration.test.ts, tests/extension/panels/panel.test.ts, tests/extension/utils.test.ts
=> Consolidate Terminal Styles

.github/workflows/release.yml, package.json, src/constants.ts, src/extension/extension.ts
Primarily for development purposes.
=> Add additional panel

package.json, src/extension/server/runmeServer.ts, src/utils/configuration.ts, tests/extension/server/runmeServer.test.ts
Ideally this will help not run into firewall issues on systems that are sensitive to making networking connections.
=> Optionally allow GRPC using Unix Domain Socket via settings

assets/runme-logo-open-dark.svg, assets/runme-logo-open-light.svg, package.json
I guess the think magic for the toolbar icons only works in insiders at the moment
=> Fix the toolbar icons in dark mode

package-lock.json, package.json, src/extension/extension.ts, src/extension/serializer.ts, src/extension/utils.ts, src/schema.ts, src/types.ts, src/utils/configuration.ts, tests/extension/configuration.test.ts, tests/extension/utils.test.ts
Goes along with https://github.com/stateful/runme/pull/428.
=> Lifecycle identity refactor

CHANGELOG.md, README.md, examples/CATEGORIES.md, examples/README.md, examples/branchGPT.md, examples/enhance/README.md, examples/fresh/README.md, examples/frontmatter/skipPrompts/DISABLED.md, examples/frontmatter/skipPrompts/ENABLED.md, examples/hardening/server.md, examples/k8s/README.md, examples/shebang.md, examples/test.md, examples/vercel/README.md, package.json, src/extension/serializer.ts, src/utils/configuration.ts, tests/e2e/specs/cell.e2e.ts, tests/extension/configuration.test.ts, walkthroughs/0-intro.md, walkthroughs/1-features.md, walkthroughs/2-annotations.md, walkthroughs/3-learn-more.md, walkthroughs/welcome.md
Switch default for v2 release.
PS: leave out `CONTRIBUTING.md` because it requires a runmejs release and fails CI/CD otherwise.
=> Enable document and cell lifecycle identity

.vscode/settings.json
=> Do not disable lifecycle identity for this repo

src/extension/__generated__/graphql.ts, src/extension/messages/cloudApiRequest/saveCellExecution.ts
Address this issue https://github.com/stateful/vscode-runme/issues/989
=> chore: making notebook id an runme_version optional

.vscode/launch.json
Adds support to run tests using the launch.json runners.
=> Includes essential environment variables in launch.json configuration

examples/redis/query.md
=> Redis query runbook revisions

package-lock.json, package.json
Likely more work to do to get tests to pass on macOS but this will make them run again.
=> Fix vscode binary download on macOS

tests/e2e/helpers/index.ts, tests/e2e/specs/identity/identity.empty-file.all.e2e.ts, tests/e2e/specs/identity/identity.empty-file.cell.e2e.ts, tests/e2e/specs/identity/identity.empty-file.document.e2e.ts, tests/e2e/specs/identity/identity.empty-file.none.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.all.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.cell.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.document.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.none.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.all.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.cell.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.document.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.none.e2e.ts, tests/e2e/specs/identity/identity.shebang.all.e2e.ts, tests/e2e/specs/identity/identity.shebang.cell.e2e.ts, tests/e2e/specs/identity/identity.shebang.document.e2e.ts, tests/e2e/specs/identity/identity.shebang.none.e2e.ts
Introduce a spinner to retry when fs operations aren't fast enough.
=> MacOS fix e2e test race

package-lock.json, package.json, src/extension/executors/runner.ts, src/extension/messages/cloudApiRequest/saveCellExecution.ts
The changes in formatting are minimal.
Closes https://github.com/stateful/vscode-runme/pull/1073.
=> Prettier fix to upgrade to 3.2.4

src/extension/messages/platformRequest/saveCellExecution.ts, src/extension/messages/platformRequest/updateCellExecution.ts
This pull request addresses an important fix related to the Share button functionality. Due to insufficient manual testing during the initial development, it wasn't noticed that this feature was incomplete and not working properly.
=> Fixing Incomplete Share Button Functionality for Platform (beta)

package-lock.json, package.json, tests/e2e/package-lock.json, tests/e2e/package.json, tests/e2e/wdio.conf.ts
Unfortunately there's always a lag after a new VS Code major release comes out.
=> Try stable and see if chromedriver is available now

src/extension/utils.ts
During the implementation of Platform Authentication, an issue was introduced affecting the current authentication flow. The panels are failing to load as a result of this issue
=> Fixes broken panels using current GH Auth

package.json, src/client/components/terminal/index.ts, src/client/components/terminal/share.ts, src/extension/__generated__/gql.ts, src/extension/__generated__/graphql.ts, src/extension/executors/runner.ts, src/extension/kernel.ts, src/extension/messages/cloudApiRequest/saveCellExecution.ts, src/extension/messages/cloudApiRequest/updateCellExecution.ts, src/extension/messages/platformRequest/saveCellExecution.ts, src/extension/messages/platformRequest/updateCellExecution.ts, src/gql/createCellExecution.graphql, src/gql/updateCellExecution.graphql, src/types.ts, tests/extension/messages/cloudApiRequest/saveCellExecution.test.ts, tests/extension/messages/platformApiRequest/saveCellExecution.test.ts
Not yet planned to be a permanent feature.
=> Escalate button experiment

examples/gcp/setup.md
Reverts stateful/vscode-runme#1144
=> Revert "Add the step to set the gcloud default"

src/client/components/env/store.ts, src/client/utils.ts, src/extension/executors/runner/factory.ts, src/extension/executors/runner/index.ts, src/extension/kernel.ts, src/extension/provider/runmeTask.ts, src/extension/runner/index.ts, src/extension/utils.ts, tests/extension/runner/runner.test.ts
Changes necessary to make smart env store (aka owl store) work with latest implementation.
=> Owl fixes to make integration work

package-lock.json, package.json, src/client/components/env/store.ts, src/client/components/envViewer.ts, src/client/utils.ts, src/extension/events/envVarsChanged.ts, src/extension/executors/runner/factory.ts, src/extension/executors/runner/index.ts, src/extension/extension.ts, src/extension/kernel.ts, src/extension/panels/notebook.ts, src/extension/provider/runmeTask.ts, src/extension/runner/client.ts, src/extension/runner/index.ts, src/extension/runner/monitorEnv.ts, src/extension/utils.ts, src/types.ts, tests/extension/runner/runner.test.ts
Connects the "Env Store" view only available in development to a data source.
=> Adds support to listen events from MonitorEnvs

src/extension/__generated-platform__/fragment-masking.ts, src/extension/__generated-platform__/gql.ts, src/extension/__generated-platform__/graphql.ts, src/gql-platform/createCellExecution.graphql, src/gql-platform/updateCellExecution.graphql, src/gql/createCellExecution.graphql
When the escalation experiment is enabled the Share Button does not appear due to a missing exit code.
=> Updated GQL stuff to fix Share button on Platform Escalation

examples/README.md, package-lock.json, package.json, src/extension/executors/runner/index.ts, src/extension/executors/task.ts, src/extension/executors/utils.ts
Using the type information in the specs provided by the mighty 🦉.
=> Handle secrets with a password prompt

codegenPlatform.ts, src/extension/__generated-platform__/graphql.ts, src/extension/messages/platformRequest/saveCellExecution.ts, tests/extension/messages/platformApiRequest/saveCellExecution.test.ts
Send notebook fileName when saving a cell output for Stateful Platform
=> Send fileName when saving a cell

package-lock.json
Latest minor fast-forwards plus selected major versions.
=> Upgrade deps prior to release

src/extension/utils.ts
This PR fixes using the wrong user session when platform is enabled.
=> Fix using the wrong user session for auto-save

package.json, src/client/components/terminal/index.ts, src/client/index.ts, src/constants.ts, src/extension/commands/index.ts, src/extension/kernel.ts, src/extension/utils.ts, src/types.ts
Create separation between Runme as a tool and [Stateful as platform](https://stateful.com/).
=> Disable any cloud collaboration features by default

package-lock.json
=> Dependencies maintenance

package-lock.json, package.json
Back to v2.9.3 because v2.9.4 is broken.
=> Downgrade Buf SDK and compiled protos

.github/workflows/release.yml, __mocks__/vscode.ts, package.json, src/extension/kernel.ts
Interactive Runme-backed terminal integration.
=> Early terminal prototype

examples/README.md, tests/e2e/wdio.conf.ts, tests/fixtures/README.md
Adding better examples for our examples/README.md file
Moving original file used by the e2e suite to a new fixtures location.
=> Update README.md example file

examples/aws/ec2.md, examples/aws/setup.md
This PRs introduces a more comprehensive guide around using AWS CLI with Runme Notebooks and Cloud renderers for EC2.
=> Update AWS Example guide

__mocks__/vscode.ts, package-lock.json, package.json, src/constants.ts, src/extension/commands/index.ts, src/extension/extension.ts, src/extension/kernel.ts, src/extension/serializer.ts, src/extension/utils.ts, tests/e2e/specs/identity/identity.existent-doc.cell.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.none.e2e.ts, tests/extension/extension.test.ts, tests/extension/serializer.test.ts
1. Use notebook UI to allow editing/redaction of outputs prior to generating Gist
2. Introduce mask/unmask
Incomplete:
=> Baseline to enable Gist feature

examples/shebang.md, src/extension/commands/index.ts, src/extension/extension.ts, src/extension/kernel.ts, src/extension/provider/codelens.ts, src/extension/serializer.ts, tests/extension/commands/index.test.ts, tests/extension/kernel.test.ts, tests/extension/serializer.test.ts
Solves https://github.com/stateful/vscode-runme/issues/1287.
=> Handle obvious corner cases for masking

package-lock.json, package.json, src/extension/executors/runner/factory.ts, src/extension/runner/index.ts
Changes required by https://github.com/stateful/runme/pull/560 to unlock functionality as described in referenced PR.
=> Unlock shebang++

catalog-info.yaml
=> chore: udpate doc structure

src/client/components/configuration/annotations.ts, src/extension/cell.ts, src/extension/provider/cellStatusBar/items/named.ts, src/schema.ts, tests/e2e/pageobjects/cell.page.ts, tests/e2e/specs/basic.e2e.ts
- Improve user feedback when updating the name field.
- Update name description
- Ask user for confirmation before adding an example cell for the referencing the cell output 
Fixes https://github.com/stateful/vscode-runme/issues/1336
=> Improve configuration feedback

package.json, src/extension/executors/runner/index.ts, src/extension/executors/task.ts, src/utils/configuration.ts, tests/extension/__snapshots__/configuration.test.ts.snap, tests/extension/configuration.test.ts
Similar to https://github.com/stateful/vscode-runme/pull/1352.
=> Set default for closeTerminalOnSuccess annotation in settings

examples/aws/ec2.md, examples/gcp/gce.md, src/extension/executors/aws.ts, src/extension/executors/gcp.ts, src/extension/executors/index.ts, src/extension/executors/resource.ts, src/extension/executors/runner/index.ts, src/extension/kernel.ts, src/extension/resolvers/awsResolver.ts, src/extension/resolvers/gcpResolver.ts, src/extension/utils.ts
If successful it will replace the interpolate with variables known in the ENV. Otherwise, it will use the original URI/URL.
=> Use runner to attempt interpolation

src/extension/cell.ts, src/extension/messages/github.ts, tests/extension/cell.test.ts
Two UX improvements as per title.
=> Annotations as JSON & actionable warning for Gist

.github/scripts/overwrites/stateful.sh
* Adds a new entry to overwrite the value of `runme.app.notebookAutoSave`
* Adds a new entry to overwrite the value of `runme.app.sessionOutputs`
=> Adds new entry to the platform defaults

.github/scripts/overwrites/stateful.sh
Override homepage so the Stateful extension goes to https://stateful.com.
=> Add homepage override.

.github/scripts/overwrites/stateful.sh
=> Stateful package words

src/extension/messages/platformRequest/saveCellExecution.ts, src/extension/messages/platformRequest/updateCellExecution.ts
Track events when saving and updating cells.
=> Add cell logs

src/extension/commands/index.ts
Summary last, as in prefix with "summary-" which alphabetically gives it lower priority.
=> Make the Gist listings on GH profile page more useful

src/extension/handler/uri.ts
Updates Stateful Platform Strings
=> Updates strings for Stateful Platform

package-lock.json, package.json, tests/extension/schema.test.ts, tests/extension/utils.test.ts
=> Upgrade deps - June 2024

examples/aws/ec2.md, examples/aws/eks.md, examples/aws/setup.md, package-lock.json, package.json, src/client/components/aws/ec2Helper.ts, src/client/components/aws/ec2InstanceActions.ts, src/client/components/aws/ec2InstanceDetails.ts, src/client/components/aws/ec2Instances.ts, src/extension/executors/aws.ts, src/extension/executors/aws/ec2.ts, src/extension/executors/aws/eks.ts, src/extension/executors/index.ts, src/extension/kernel.ts, src/extension/messages/aws.ts, src/extension/resolvers/awsResolver.ts, src/types.ts
Adds initial support to handle specific **AWS_PROFILES** for Cloud Renderers.
=> feat(CloudRenderers): Initial AWS_PROFILE handling

CONTRIBUTING.md
Config `NODE_OPTIONS` in `test` and `test:unit` so node can resolve ESM modules.
=> Config NODE_OPTIONS

.github/workflows/test.yml, src/extension/__generated-platform__/graphql.ts, src/extension/messages/cloudApiRequest/saveCellExecution.ts, src/extension/messages/platformRequest/saveCellExecution.ts, src/extension/utils.ts, tests/extension/messages/platformApiRequest/saveCellExecution.test.ts, tests/extension/utils.test.ts, vitest.conf.ts
Send notebook file contents and git relative path to the Platform.
=> Send file contents

src/client/components/aws/ec2InstanceDetails.ts
=> Temporary disabling SSH Command

examples/azure/vms.md
This pull request introduces an initial approach for managing Microsoft Azure virtual machines (VMs).
=> Add initial azure examples

package.json
Might help to more explicitly explain here what these things are, sort of define DevOps Notebook in a way.
=> More descriptive marketplace description

package-lock.json
Let's see if tests are passing.
=> One fell swoop deps upgrade

.github/scripts/overwrites/stateful.sh
I think it's importat to describe a relationship with runme
=> Runme in Stateful package description

src/extension/messages/platformRequest/saveCellExecution.ts, tests/extension/messages/platformApiRequest/saveCellExecution.test.ts
Use the notebook reference to access the fsPath.
=>  Fix fsPath reference

.github/scripts/overwrites/stateful.sh, src/extension/__generated-platform__/fragment-masking.ts, src/extension/__generated-platform__/graphql.ts, src/extension/extension.ts, src/extension/kernel.ts, src/extension/messages/platformRequest/saveCellExecution.ts, src/extension/serializer.ts, tests/extension/messages/platformApiRequest/saveCellExecution.test.ts
Send session outputs to the Platform API.
=> Enable Platform session cache

package-lock.json, package.json, tests/e2e/package-lock.json, tests/e2e/package.json, tests/e2e/wdio.conf.ts
We had issues when VS Code v1.90 was first released. Let's see if that's resolved.
=> Run tests against latest vscode

src/extension/extension.ts
Add a shortcut to open the Stateful platform.
=> Adds Open Dashboard button

src/extension/executors/gcp/gke/clusters.ts
The bug is occurring because the request to retrieve the machine type requires the zone, but we were passing the region when the cluster is actually regional.
In the case of a regional cluster, multiple zones are listed in `cluster.locations`. Therefore, it is now necessary to display the count of nodes, total CPU, and total memory requesting the machine type for each zone.
Closes #1510
=> Adds support to render Regional GKE Clusters

package-lock.json, package.json, tests/e2e/package-lock.json, tests/e2e/package.json
Dependabot updates for @wdio/local-runner and @wdio/mocha-framework
=> Unified dependabot updates

package-lock.json, package.json, src/extension/__generated-platform__/graphql.ts, src/extension/messages/platformRequest/saveCellExecution.ts
Send device info to the Platform. This PR depends on https://github.com/stateful/platform/pull/819
=> Send device info

package-lock.json, package.json, src/extension/ai/stream.ts
Make upstream PR build and pass tests.
=> Fix imports

.github/dependabot.yml
Includes:
- Time / Timezone: 09:00 America/Los_Angeles
- Group: @aws-sdk/*
=> Updates dependabot config

.github/scripts/overwrites/stateful.sh, package.json, walkthroughs/0-intro.md
Update descriptions to own the Runme Notebooks term a little more clearly
=> Marketplace naming update

src/client/components/terminal/actionButton.ts, src/client/components/terminal/index.ts, src/client/components/terminal/share.ts
Splits terminal buttons to have separate business logic and conditions.
=> Splits terminal buttons

package.json, src/extension/__generated-platform__/gql.ts, src/extension/__generated-platform__/graphql.ts, src/extension/commands/index.ts, src/extension/environment/manager.ts, src/extension/extension.ts, src/gql-platform/getUserEnvironments.graphql, tests/extension/extension.test.ts
Select an environment from the Platform to work on. This POC demonstrates how users can interact with environments, setting the foundation for future features like variables.
https://github.com/user-attachments/assets/402a7608-cb7b-425c-9456-4c2e587983f1
Depends on https://github.com/stateful/platform/pull/864
=> Integrate environments

src/extension/extension.ts
The Extension Initialization was having a UI blocking due to it was awaiting the **showInformationMessage** finishes.
=> Unblocking extension init

.vscode/launch.json, __mocks__/vscode.ts, src/extension/extension.ts, src/extension/kernel.ts, src/extension/server/kernelServer.ts, src/extension/utils.ts, tests/extension/extension.test.ts, tests/extension/kernel.test.ts, tests/extension/server/kernelServer.test.ts
Introducing anonymous telemetry that respects common ENV var DO_NOT_TRACK=true or DO_NOT_TRACK=1.
=> Telemetry (turn off with DO_NOT_TRACK env var)

package-lock.json, package.json, tests/e2e/package-lock.json
Unified Dependabot updates.
Excludes the update to Typescript 5.6 https://github.com/stateful/vscode-runme/pull/1634
=> Dependabot 20240919

src/extension/extension.ts
Enhances current message with one more engaging.
=> Improves shell detection error message

.github/workflows/sonarcloud.yml
Disables SonarCloud integration, preserved in a separate Github Action.
=> Disables SonarCloud

src/extension/serializer.ts, src/extension/utils.ts, tests/extension/serializer.test.ts
Commit messages document motivation behind the individual changes.
=> Minor naming changes

package.json
=> Enable Escalations for Runme

CONTRIBUTING.md, package.json, src/client/components/configuration/annotations.ts, src/client/components/configuration/categorySelector.ts, src/extension/commands/index.ts, src/extension/extension.ts, src/extension/messages/platformRequest/saveCellExecution.ts, src/extension/provider/launcher.ts, src/extension/quickPickItems/category.ts, tests/extension/extension.test.ts, tests/extension/provider/launcher.test.ts, tests/extension/utils.test.ts
=> Minor Fixes and Enhancements

package.json, src/extension/index.ts, src/extension/server/kernelServer.ts, src/extension/utils.ts, src/utils/configuration.ts, tests/extension/server/kernelServer.test.ts
This allows us to turn off all telemetry at the window level.
=> Introduce extension level telemetry toggle

src/extension/panels/cloud.ts
Work within the observables rather than maintaining auxiliary state.
=> Review suggestions for "Add sign-out event handling and panel HTML refresh for CloudPanel"

.github/workflows/release.yml, package-lock.json, package.json, src/extension/index.ts, webpack.config.ts
As per https://learn.microsoft.com/en-us/azure/azure-monitor/app/migrate-from-instrumentation-keys-to-connection-strings.
=> Upgrade vscode-telemetry

README-platform.md, package.json, src/constants.ts, src/extension/provider/statefulAuth.ts
- Added functionality to dismiss login notifications for improved user experience.
- Renamed the button label from "Open Dashboard" to "Open Workspace" to better align with the intended functionality.
- Renamed "Commands" Webview to "Cloud"
=> Allow dismissing login notifications and update button label

examples/k8s/package-lock.json, package-lock.json, package.json
Ignored due to failed tests:
- #1838
- #1836
- #1816
=> Dependabot updates 2024-12-06

.github/scripts/overwrites/runme.md, .github/workflows/release.yml, package.json, src/extension/kernel.ts, src/extension/messages/platformRequest/saveCellExecution.ts, src/types.ts, tests/extension/messages/platformApiRequest/saveCellExecution.test.ts
Turn default on in `pre-release` for a few days ahead of `stable`.
=> Reporter API in pre-release

src/extension/extension.ts, src/extension/kernel.ts
This update addresses a race condition where feature flags were not reliably available during the extension’s initialization process.
=> Fix features flags loading

.github/scripts/overwrites/runme.md, .github/workflows/release.yml, package.json
We've tested this in pre-release since early 2024Q4.
=> Flip Reporter API feature flag to default enabled

src/extension/signedIn.ts
SignedIn no longer reports cell runs. This fixes it.
I believe this broke with https://github.com/stateful/vscode-runme/pull/1861.
=> Fix for StatefulAuthProvider's change in behavior

src/extension/serializer/serializer.ts, tests/extension/serializer.test.ts
This effectively makes `dagger shell` default for newly created notebook, e.g. `mynotebook.dag`.
=> Set Dagger shell for empty .dag notebooks

src/extension/extension.ts, src/extension/handler/uri.ts, src/extension/handler/utils.ts, src/extension/utils.ts
This PR adds a new URI handler command that enables running specific notebook cells through the Cloud Platform integration. This allows external systems to trigger selective cell runs in **Runme** notebooks via URI commands.
=> Add support for Cloud Platform cell run via URI handler

package.json, src/extension/ai/ghost.ts, src/extension/ai/manager.ts, src/types.ts
Just a visual cue, really, but I think it helps elevate confusion with LLM latency.
Default enabled in feature flags. Can be disabled via `"runme.features.AIProgress": false,` in `settings.json`.
https://github.com/user-attachments/assets/7c1e2b08-db27-417d-be65-b523b995f7f3
=> Use vscode's withProgress API to inform user AI's thinking

package-lock.json, package.json
=> chore(deps): Maintenance March 1, 2025

package-lock.json
=> Bump deps March 12, 2025

CHANGELOG.md, CONTRIBUTING.md, README-platform.md, README.md, catalog-info.yaml, dagger/CONCEPT.md, dagger/Pipeline.md, dagger/README.md, dagger/notebook/shell.dag, examples/test.md, package.json, src/extension/serializer/serializer.ts, tests/e2e/specs/githubAction.e2e.ts, tests/extension/github.test.ts, tests/extension/utils.test.ts, walkthroughs/0-intro.md, walkthroughs/1-features.md
Search/replace old with new sites.
=> Move from stateful to runmedev org as part of CNCF sandbox admission

.vscodeignore, src/client/components/terminal/index.ts, src/client/index.ts, tsconfig.json, webpack.config.ts
These changes shouldn't change the behavior of the webcomponents in the extension.
=> Enable external consumption of components

package-lock.json
Fast forward to latest protos.
=> chore(deps): March 20, 2025

.github/workflows/pipeline.yml, .gitignore, dagger/BUILD.md, tests/e2e/helpers/index.ts
The container image backing Dagger functions has binaries and libraries.
=> GHA xvfb-less

tests/e2e/helpers/index.ts, tests/e2e/specs/identity/identity.empty-file.all.e2e.ts, tests/e2e/specs/identity/identity.empty-file.cell.e2e.ts, tests/e2e/specs/identity/identity.empty-file.document.e2e.ts, tests/e2e/specs/identity/identity.empty-file.none.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.all.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.cell.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.document.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.none.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.all.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.cell.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.document.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.none.e2e.ts, tests/e2e/specs/identity/identity.shebang.all.e2e.ts, tests/e2e/specs/identity/identity.shebang.cell.e2e.ts, tests/e2e/specs/identity/identity.shebang.document.e2e.ts, tests/e2e/specs/identity/identity.shebang.none.e2e.ts
🤔 maybe, just maybe, this might reduce the flake rate.
=> Use async shell out to revert changes

dagger/BUILD.md, dagger/package-lock.json, dagger/package.json, dagger/src/index.ts, tests/e2e/wdio.conf.ts
See https://github.com/runmedev/vscode-runme/pull/2075 for details.
=> Expand Dagger module to include pre-built extensions

tests/e2e/specs/identity/identity.empty-file.all.e2e.ts, tests/e2e/specs/identity/identity.empty-file.cell.e2e.ts, tests/e2e/specs/identity/identity.empty-file.document.e2e.ts, tests/e2e/specs/identity/identity.empty-file.none.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.all.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.cell.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.document.e2e.ts, tests/e2e/specs/identity/identity.existent-cell.none.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.all.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.cell.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.document.e2e.ts, tests/e2e/specs/identity/identity.existent-doc.none.e2e.ts, tests/e2e/specs/identity/identity.shared.ts, tests/e2e/specs/identity/identity.shebang.all.e2e.ts, tests/e2e/specs/identity/identity.shebang.cell.e2e.ts, tests/e2e/specs/identity/identity.shebang.none.e2e.ts
=> Account for proxing

package-lock.json
No difference in functionality.
=> Latest protos after unnesting

package.json, src/client/components/terminal/index.ts, src/extension/kernel.ts
Disabling them for now, and removing them eventually.
=> Disable cloud features
