runmedev/vscode-runme

- src/client/components/deno.ts
- src/client/index.ts
- src/extension/constants.ts
- src/extension/executors/deno/deploy.ts
- src/types.ts
- Respect `DENO_PROJECT_NAME` if set
- Display production URL after promotion
> Improved deno deploy UX

- CONTRIBUTING.md
If GitHub's `gh` CLI is installed. If not, it'll just prompt for the token.
> Make WASM download a no-brainer

- examples/README.md
- src/extension/notebook.ts
This patch is a proposal to just have non supported languages being rendered as plain markdown, e.g.:
> Render non supported languages as markdown

- .gitignore
- __mocks__/vscode.ts
- package.json
- src/extension/commands/index.ts
- src/extension/executors/script/utils.ts
- src/extension/extension.ts
- src/extension/index.ts
- src/extension/kernel.ts
- src/extension/notebook.ts
- tests/extension/commands/index.test.ts
- tests/extension/extension.test.ts
- tests/extension/kernel.test.ts
- vitest.conf.ts
- webpack.config.ts
refs #28
As a first step to debug this issue this patch adds some logging for when initialisation for the extension fails. For that I did some minor refactoring to make code a bit more testable.
> Add initialisation logging and test coverage

- src/extension/executors/task.ts
- src/extension/executors/utils.ts
- src/extension/utils.ts
- tests/extension/executors/utils.test.ts
- tests/extension/utilts.test.ts
fixes #32
This patch includes:
- moving code into utils file for better testability
- unit test coverage for handling export lines in shell code
- support exports with single quotes (e.g. `export Foo='bar'`)
> More improvements to export statements

- __mocks__/vscode.ts
- assets/runme-logo-dark.svg
- assets/runme-logo-light.svg
- package.json
- src/extension/commands/index.ts
- src/extension/extension.ts
- tests/extension/commands/index.test.ts
- tests/extension/extension.test.ts
addresses https://github.com/stateful/vscode-runme/issues/51
> options to open runme as text editor and text-edit md as runme

- src/extension/extension.ts
- src/extension/index.ts
- src/extension/notebook.ts
- src/extension/serializer.ts
- src/types.ts
- tests/extension/extension.test.ts
Working branch to test and work out integration.
Note: dev wasm lib needs to be manually copied for now. Not expecting tests to pass until PR is finalized.
> De-/Serialization to allow full bidirectional notebook editing

- .github/scripts/downloadWasm.js
As we ramping up to get authoring/editing out the door we need a transitionary period where both exist. Want to me sure no accidents happen in the release pipeline etc.
> Make sure dev won't accidentally bleed into releases

- .vscodeignore
- webpack.config.ts
Do we still have to include `node_modules` in packaging?
I believe in the past we kept the `node_modules` because of the web component stuff, no?
> Lower bundle size

- package.json
- src/extension/commands/index.ts
- src/extension/kernel.ts
- src/extension/serializer.ts
- src/extension/utils.ts
- tests/extension/serializer.test.ts
- tests/extension/utilts.test.ts
- vitest.conf.ts
This update allows to save new files created within the `runme` notebook, e.g.:
As you can see, a second save is not possible due to our restriction. My suggestion here is to allow disable this through a configuration.
> Allow users to store a new Runme notebook file

- src/extension/executors/utils.ts
- tests/extension/executors/utils.test.ts
This will change the behavior of using `$(...)` expressions inside of exported ENV vars `export MY_VAR=$(echo 'test')`.
Old behavior inside of Runme notebook; notice gap (it's a `\n` but displayed as space by the markdown renderer) inside of MY_VAR:
```sh
$ export MY_CWD="$(pwd)"
$ export MY_VAR="$MY_CWD:$PATH"
$ echo $MY_VAR
/Users/sourishkrout/Projects/stateful/oss/runme :/Users/sourishkrout/.wasmtime/bin:/opt/homebrew/opt/libpq/bin:/Users/sourishkrout/go/bin:/Users/sourishkrout/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/sourishkrout/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/Library/Apple/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sourishkrout/.cache/zsh4humans/v5/fzf/bin
```
New behavior; no special endings (e.g. '\n'):
```sh
$ export MY_CWD="$(pwd)"
$ …
```
> Mimic POSIX var substitution behavior

- __mocks__/vscode.ts
- package.json
- src/extension/constants.ts
- src/extension/extension.ts
- src/extension/handler/uri.ts
- src/extension/handler/utils.ts
- tests/extension/extension.test.ts
- tests/extension/handler/uri.test.ts
- tests/extension/handler/utils.test.ts
This patch adds a uri handler that would allow us to have a link like `vscode://stateful.runme?command=setup&repository=git@github.com:webdriverio/webdriverio.git` anywhere to have users check out a project locally with Runme. An initial POC looks like this:
If users don't have Runme installed the following message will be displayed and allows users to immediately get started:
> Open in Runme

- __mocks__/vscode.ts
- src/extension/handler/uri.ts
- src/extension/handler/utils.ts
- tests/extension/handler/uri.test.ts
This is an addition to https://github.com/stateful/vscode-runme/pull/159 which allows one to set up a project with an url of a single markdown file, e.g. using a gist. The url has to be as follows:
```
vscode://stateful.runme?command=setup&fileToOpen=https://raw.githubusercontent.com/stateful/vscode-runme/main/examples/k8s/README.md
```
> Support set-up by file

- src/extension/kernel.ts
If there's a non-code block before a code block, it'll break from the checking loop pre-maturely. So I think we have to use `continue` here instead.
> Fix annotations not saving if file has markdown blocks

- package-lock.json
- package.json
- src/client/components/annotations.ts
- src/client/index.ts
- src/client/utils.ts
- src/constants.ts
- src/extension/provider/annotations.ts
- src/extension/utils.ts
- src/schema.ts
- src/types.ts
- tests/extension/provider/annotations.test.ts
- tests/extension/schema.test.ts
- tests/extension/utils.test.ts
Unfinished. What's left:
Error handling mechanism:
The original PR throws an error when finding invalid values. The latest version introduces safe defaults so that the Notebook can be opened (it fallbacks to the annotation's default values). The idea is that the user can still run the code block while seeing an error message that the configuration values are using the wrong data. This gives the user to fix the issue and save it. We are also displaying validation messages on the editing experience.
https://user-images.githubusercontent.com/4001529/218818809-3efca890-6b9b-4ec7-bf45-1e078c3b3c2f.mp4
> Baseline modeling of annotations to allow data validation

- src/extension/executors/runner.ts
- src/extension/executors/task.ts
- src/extension/executors/utils.ts
- src/extension/kernel.ts
- src/extension/provider/background.ts
- src/extension/runner.ts
- src/extension/utils.ts
- tests/extension/executors/utils.test.ts
Needs changes in runme service:
> Runner service implementation feature parity

- .github/scripts/checkRelease.js
- .github/scripts/downloadAndExtract.js
- .github/workflows/binaries.yml
- package-lock.json
- package.json
Introducing a new GitHub action for distributing the extension with the new Runme binaries.
Operating System Support Matrix:
- Linux ARM64, X64
- MacOS (Darwin ARM64, X64)
- Windows (win32-X64, win32-arm64)
It supports specific runme versions or use latest as default, non stable and draft releases are **not** supported
> Add new extension distribution with binaries

- __mocks__/vscode.ts
- package.json
- src/extension/extension.ts
- src/extension/server/runmeServer.ts
- src/utils/configuration.ts
- tests/extension/__snapshots__/utils.test.ts.snap
- tests/extension/configuration.test.ts
- tests/extension/extension.test.ts
- tests/extension/handler/uri.test.ts
- tests/extension/provider/launcher.test.ts
- tests/extension/server/runmeServer.test.ts
Implements the feedback I gave in #245 .
In summary:
- Binary path configuration now points to the binary itself, rather than the enclosing folder
- There is one singular function for finding the binary path, `getBinaryPath`
- The extension root Uri is passed down as a Uri, rather than as a string (avoids unnecessary (re)-parsing)
- Relative binary paths now act relative to the current workspace folder, rather than relative to extension folder
> Improve path configuration/resolution

- package-lock.json
- package.json
- src/extension/server/runmeServer.ts
- src/extension/utils.ts
- tests/extension/__snapshots__/utils.test.ts.snap
- tests/extension/server/runmeServer.test.ts
Runs one session per window, with incremental port assigning.
Note that there will be a race condition here (between deciding the port and running the server, the port can become occupied). The only way to avoid this would be putting the port assignment code on go, or by adding resilience to binding errors in the server process launch logic.
> One session per window

- __mocks__/vscode.ts
- src/extension/provider/annotations.ts
Prompt users to select a notebook kernel instead of the raw error message.
> Better handle kernel selection error

- __mocks__/vscode.ts
- src/extension/extension.ts
- src/extension/grpc/client.ts
- src/extension/kernel.ts
- src/extension/runner.ts
- src/extension/serializer.ts
- src/extension/server/runmeServer.ts
- tests/extension/extension.test.ts
- tests/extension/runner.test.ts
- tests/extension/server/runmeServer.test.ts
Makes runme server resistant against closing, as long as it is caught by the `onClose` callback.
Might want to think about polling/regular health checks in case something more dubious occurs. (Long-term)
Should be functional, just need to write/fix tests at this point.
> Auto-Restart server on `onClose`

- src/extension/executors/runner.ts
- src/extension/executors/task.ts
- src/extension/kernel.ts
- src/extension/runner.ts
Significantly improves the error handling situation for gRPC runner. Included is:
- Handle case where server is disconnected prematurely and close terminal (previously terminal task would hang)
- If grpc runner fails, show error message to user
- If grpc environment creation fails, show error message to user
> Improve gRPC runner error handling

- src/extension/executors/utils.ts
- src/extension/kernel.ts
Windows does not have a `$SHELL` environment variable, so it becomes our responsibility to detect the location of the shell. 
Basically, until #312 is solved, it's probably best to hard disable the gRPC runner on windows, since we don't know where the shell is.
> Hard disable grpc runner on windows

- .github/scripts/getLastStableRelease.js
`os.platform()` returns in Windows `win32` while our download directory lists Windows artifacts as e.g. `0.6.5/runme_windows_x86_64.zip`.
> fix `getLastStableRelease` for Windows

- examples/README.md
- package-lock.json
- package.json
- src/extension/runner.ts
- tests/extension/runner.test.ts
Solves #252 
Added a section to `examples/README.md` to test against.
> Support terminal dimensions in gRPC runner

- src/extension/commands/index.ts
- src/extension/extension.ts
- src/extension/server/runmeServer.ts
- tests/extension/commands/index.test.ts
This fixes the CLI button for use with the gRPC runner. Needs version of binary including stateful/runme#202 (built from main)
Not sure whether to pass everything as command line parameters, or environment variables. I used environment variables because it looks cleaner (and allows users to easily run other commands in the same session), but a lot is then "hidden" from the user. Thoughts @sourishkrout ?
> Integrate CLI button with gRPC runner

- src/extension/commands/index.ts
- src/extension/provider/cli.ts
- tests/extension/commands/index.test.ts
Fixes #288 
Removes parts of the code that require runme installed - we should just use the bundled/configured one instead.
> Remove check for runme to be installed

- src/schema.ts
- tests/extension/schema.test.ts
We will have fewer edge cases "without default" than introducing them starting their lifecycle in the extension.
There is more work to be done here but it's important to get this fix in for now.
> Remove runner incompatible default

- src/extension/extension.ts
- src/extension/server/runmeServer.ts
- src/utils/configuration.ts
- tests/extension/server/runmeServer.test.ts
This PR does the following:
- Fix relaunch behavior on close, which could sometimes be called in tandem with the relaunch behavior on error, causing two concurrent relaunches
- Create TLS certificates in a different directory per-window rather than globally 
- This behavior is overridden when a specific TLS directory is set - so the issue will still exist when the user specificies a directory, because runme CLI will always generate a new certificate on launch rather than reading an existing one)
- Clean up some logic in the runme server to be iterative rather than recursive, which helps for debugging & code clarity
> Fix relaunch behavior in runme server logic + window-specific certificates

- src/client/components/terminal.ts
<p align="center">
</p>
Mimics style of VSCode
Was not able to get the scrollbar to transition (fade in/out), apparently `::-webkit-scrollbar-thumb` doesn't allow transitions - @christian-bromann do you have any ideas here as to if VSCode could've accomplished this with pure css?
> Native scrollbar in Notebook Terminal

- src/extension/executors/runner.ts
- src/extension/executors/utils.ts
- tests/extension/executors/utils.test.ts
Along with stateful/runme#189, this improves the command normalization situation for the gRPC runner.
> Disable grpc runner command normalization

- src/client/components/terminal.ts
This forces a terminal focus when the window focues.
Before this, short clicks can sometimes fail to focus the terminal.
Unfortunately, this creates a "flicker effect" where you try to focus the terminal, it unfocuses, and then refocuses as a result of this PR. I figure this behavior is better than staying unfocused after clicking.
I am still not sure what is causing the issue in the first place, so this is effectively a work-around.
> Force focus notebook terminal on window focus

- src/extension/provider/launcher.ts
- tests/extension/provider/launcher.test.ts
The original version had leading slashes on all entries. This changes will make the tree view match the explorer view.
> Match explorer's UX: no leading slashes

- src/client/components/terminal.ts
I don't think it's necessary to cache position to ensure not running fit, since it needs to be run every resize anyway.
This PR will be needed for implementing terminal (PTY) resizing.
> Fix notebook terminal resizing

- walkthroughs/0-intro.md
- walkthroughs/1-annotations.md
- walkthroughs/3-features.md
Using `runme.dev/img/....` image path don't work as file paths can change after every deploy. This patch replaces them using github links.
> Fix image paths for walkthrough images

- package-lock.json
- package.json
- src/extension/grpc/client.ts
- src/extension/grpc/healthTypes.ts
- src/extension/server/runmeServer.ts
- tests/extension/extension.test.ts
- tests/extension/server/runmeServer.test.ts
Detect whether gRPC server exists using `grpc/grpc` healthcheck rather than using the parser client directly. This is more in line with gRPC standard practice and gives us more options down the line.
> Use gRPC health check for runme server

- src/extension/terminal/terminalState.ts
I made a mistake when adding this line. 
This PR prevents console from being overwhelmed with error messages on interactive scripts.
> Fix unnecessary error tracking Notebook Terminal input

- src/client/components/terminal.ts
If there is no `--vscode-terminalCursor-foreground` variable, this will revert to the foreground color instead.
This fixes the terminal cursor not appearing in the `Github Light (Colorblind)` theme.
> Fix notebook terminal cursor color

- src/extension/executors/runner.ts
- src/extension/executors/utils.ts
- src/extension/utils.ts
- tests/extension/executors/utils.test.ts
- tests/extension/utils.test.ts
Executes sequences like `$ echo Hello` as `echo Hello`
Note that this will affect sequences such as:
```
export VAR="
$
"
```
Though usually `$` are escaped in bash so I imagine this kind of a thing to be rather uncommon.
> Parse out trailing dollar signs in cmd sequences

- src/client/components/terminal.ts
- src/client/fitAddon.ts
Fixes #383 
This includes a "fork" of the fit addon from xtermjs, where we make the requisite calculations more directly. We are potentially susceptible to breakage on a dependency update - hopefully these will get caught by e2e tests #357
> Fix Notebook Terminal infinitely resizing

- package.json
- src/extension/kernel.ts
- src/utils/configuration.ts
- tests/extension/configuration.test.ts
Adds two configurations, `runme.terminal.fontSize` and `runme.terminal.fontFamily`.
> Allow font customization in Notebook Terminal

- package.json
- src/client/components/terminal.ts
- src/client/fitAddon.ts
- src/client/index.ts
- src/extension/kernel.ts
- src/types.ts
- src/utils/configuration.ts
Allows user to define config `runme.terminal.rows` for the initial row setting for a terminal.
Also adds vertical drag handle, to adjust number of rows.
**Known Issues**:
- The number of rows resets when re-running a cell. We would need to code a persistence layer to change this
- Terminal is not "focused" when dragging.
> Allow custom rows/vertical resizing in Notebook Terminal

- __mocks__/vscode.ts
- src/extension/commands/index.ts
- src/extension/executors/runner.ts
- src/extension/extension.ts
- src/extension/provider/background.ts
- src/extension/utils.ts
- src/types.ts
- tests/extension/configuration.test.ts
- tests/extension/provider/background.test.ts
- tests/extension/provider/launcher.test.ts
- tests/extension/utils.test.ts
Implements background as singleton instance.
As a bonus, the "Stop Task" button should now disappear when the task either is closed or is otherwise no longer running. This is now possible since it is clear where the associated task is.
At a low-level, this is all accomplished by attaching the grpc runner object instance to the terminal object.
> Background as singleton

- package-lock.json
- package.json
- src/extension/commands/index.ts
- src/extension/executors/runner.ts
- src/extension/extension.ts
- src/extension/provider/background.ts
- src/extension/runner.ts
- src/types.ts
- tests/extension/extension.test.ts
- tests/extension/provider/background.test.ts
- tests/extension/runner.test.ts
- When running, "Background Task" becomes "PID: ####" (for background tasks)
- When clicked on, this opens the task's integrated terminal
- Removed PID from "Open Terminal" button
Note that this feature requires the latest stateful/runme executable (on main branch, not release)
> Use PID for background task

- .github/workflows/release.yml
Fixing OpenVSX publishing for platform-specific targets the format is namespace.extension-version@target.vsix.
> Fix OpenVSX publishing

- package-lock.json
- package.json
This PR restores test coverage
We can also close #401
> Bump `@vitest/coverage-c8` to `v0.30.1` (restore test coverage)

- src/extension/executors/runner.ts
- src/extension/provider/runmeTask.ts
- src/extension/runner.ts
Non-text outputs are broken due to #445, since we're mangling all non-interactive outputs.
This PR now only does the convert eol functionality on non-interactive cells with type `text/plain`
> Fix non-text outputs

- src/extension/extension.ts
- tests/extension/extension.test.ts
> Prefer `vscode.openWith` over `vscode.open`

- .github/workflows/test.yml
- CONTRIBUTING.md
Instead of re-defining our set-up process in CI again, let's use Runme to re-purpose our documentation.
I currently use the original CLI:
```sh
npx runme run --filename=CONTRIBUTING.md configureNPM
npx runme run --filename=CONTRIBUTING.md setup
npx runme run --filename=CONTRIBUTING.md build
npx runme run --filename=CONTRIBUTING.md test
```
instead of the experimental one:
```sh
npx runme2 configureNPM setup build test
```
Let me know if you prefer the experimental one instead.
> Use runme for setting up test pipeline

- __mocks__/vscode.ts
- src/extension/kernel.ts
- src/extension/serializer.ts
- tests/extension/serializer.test.ts
Fixes #461 
In the future we should probably return a more detailed response from the serialize request, and then use that to update the metadata.
> Update cell names on save

- __mocks__/vscode.ts
- package-lock.json
- package.json
- src/extension/executors/runner.ts
- src/extension/provider/runmeTask.ts
- src/extension/utils.ts
- src/utils/configuration.ts
- tests/extension/utils.test.ts
Gives the user configuration to set dotenv file schema, and to toggle it in general.
Part of stateful/runme#234
Note that environment variables set in dotenv files "persist," so even if you delete it from a dotenv file, it will still exist in the runner session. Fixing this will require changes to the behavior and/or API of the grpc server.
> Parse dotenv files

- __mocks__/vscode.ts
- src/extension/executors/runner.ts
- src/extension/executors/shell.ts
- src/extension/executors/task.ts
- src/extension/executors/vercel/deploy.ts
- src/extension/handler/uri.ts
- src/extension/handler/utils.ts
- src/extension/index.ts
- src/extension/kernel.ts
- src/extension/logger.ts
- src/extension/provider/runmeTask.ts
- src/extension/server/runmeServer.ts
- src/extension/survey.ts
- src/extension/utils.ts
- tests/extension/configuration.test.ts
fixes #454
This is a simple patch that makes Runme log into an dedicated output channel. I kept it intentionally simple for now as we don't know yet many requirements for our logging. For now, this gives us a central point/module to handle logging. I looked into existing logging package which all seem overkill and came with some issues, e.g. [@vscode-logging/logger](https://github.com/SAP/vscode-logging/blob/master/packages/logger) would print out a JSON blog rather than a simple log line.
Something I would have liked to address but is not possible at the moment:
- colors in output channel: currently not supported (see https://github.com/microsoft/vscode/issues/571)
- add a command to copy out all logs from our channel to support users debugging issues: also currently not supported …
> Runme logging in output channel

- src/client/components/annotations.ts
- src/client/components/closeCellButton.ts
- src/client/components/outputItems.ts
- src/client/components/terminal.ts
- src/client/components/vercel.ts
- src/client/index.ts
- src/client/utils.ts
- src/constants.ts
- src/extension/cell.ts
- src/extension/kernel.ts
- src/extension/messages/cellOutput.ts
- src/types.ts
- tests/extension/messages/cellOutput.test.ts
Introducing a close-button component, only supported by the Annotations component so far.
https://github.com/stateful/vscode-runme/assets/4001529/eadfeaaa-a070-43e3-bd08-d895cb4d4737
Fixes https://github.com/stateful/vscode-runme/issues/500
> Close cell output

- __mocks__/vscode.ts
- src/extension/provider/codelens.ts
- tests/extension/runner.test.ts
Fixes stateful/runme#269
The `TextRange` information reported from grpc gives offset in bytes, but VSCode expects offset in characters.
My solution was to count the lines manually with rudimentary string operations. This has comically awful performance, but doing it the "right" way is tough, since we'd need to iterate through characters.
For now it should be fine on small-ish files. But if we run into problems with performance for CodeLens, this is the first thing to optimize. [I found a library too](https://www.npmjs.com/package/codepoint-iterator) that could be of help.
Another thing: anything that's not `utf-8` and has wide characters will almost certainly break. VSCode does not appear to let you determine the encoding of a `TextDocument` - see microsoft/vscode#824 - so we can't really …
> Convert textRange bytes to characters

- src/extension/extension.ts
Avoid confusion while reviewing diffs. It will basically avoid scenarios like these:
> Remove transient metadata keys from diffs

- package.json
- src/extension/commands/index.ts
- src/extension/serializer.ts
- src/utils/configuration.ts
- tests/extension/commands/index.test.ts
- tests/extension/configuration.test.ts
Requires stateful/runme#293
CLI button now uses cell index rather than cell name. Note that this feature will break for users who don't upgrade to the latest runme.
This unblocks us on [this issue](https://github.com/stateful/vscode-runme/issues/566#issuecomment-1574128419), though it doesn't solve it.
I also introduced `runme.cli.useIntegratedRunme`, which makes it easier to test the new version of runme (uses integrated path).
> Run CLI with index rather than cell name

- __mocks__/vscode-telemetry.ts
- package.json
- src/extension/extension.ts
- src/extension/utils.ts
- tests/extension/extension.test.ts
- tests/extension/utils.test.ts
> As a repository maintainer I want to have developers open an e.g. `CONTRIBUTING.md` file every time they start the project. 
This patch adds a `runme.flags.startFile` setting that allows to define a file to be opened by Runme at application start. This would be helpful for anyone that has an important file for contributor to look at to have it opened when VS Code starts. Especially for developers defining a `devcontainer.json` file it could allow new contributors to see all important documentation and commands to start get productive.
If the file is not existing in the repository, it will just return silently. This allows devs to have a global configuration to always open e.g. a `CONTRIBUTING.md` file if existing. Otherwise this option is meant to be used mainly in …
> Allow to define a start-up file to be opened by Runme when extension activates

- package.json
- src/constants.ts
- src/extension/commands/index.ts
- src/extension/extension.ts
- src/extension/messaging.ts
- src/extension/utils.ts
- tests/extension/commands/index.test.ts
- tests/extension/extension.test.ts
- tests/extension/messaging.test.ts
- tests/extension/utils.test.ts
Prompt the user to add the extension to recommended extensions
Note: It does not cover Multi-root workspace for now.
- It prompts the user on Extension Activation (unless disabled by the user)
- It supports don't ask again feature
- Added as a command in order to bring it back again
🎥 Demo 
https://github.com/stateful/vscode-runme/assets/4001529/f8085ef4-1a51-4c9b-b832-9b05bda15181
Fixes https://github.com/stateful/vscode-runme/issues/520
> Add Runme to recommended extensions

- src/extension/serializer.ts
- src/extension/utils.ts
- tests/extension/serializer.test.ts
- tests/extension/utils.test.ts
It dates back to when the serializer part of the parser was "experimental".
Also, tests coupled with WASM Serializer are obsolete. Serialization testing is now covered in https://github.com/stateful/runme.
PS: Relevant code makes saving fail when the markdown diff editor is active.
> Presave check is no longer required

- src/extension/executors/runner.ts
- src/extension/executors/utils.ts
- src/extension/kernel.ts
- src/extension/provider/runmeTask.ts
- src/extension/runner.ts
- src/extension/utils.ts
- tests/extension/executors/utils.test.ts
- tests/extension/runner.test.ts
- tests/extension/utils.test.ts
Ignores `export` lines if they would override an environment variable in the system store or `.env` files.
Solves #643
> don't prompt for preexisting environment variables

- src/client/components/copyButton.ts
- src/client/components/icons/save.ts
- src/client/components/icons/share.ts
- src/client/components/terminal/index.ts
- src/client/components/terminal/share.ts
This PR introduces a saving state icon and fixes button color theme inconsistency.
🎥  Saving state
🎥  Color fix
Solves https://github.com/stateful/vscode-runme/issues/675
> Add save status icon and fix buttons color

- examples/README.md
- src/client/components/configuration/annotations.ts
- src/extension/cell.ts
- src/schema.ts
Introduces `terminalRows` to select the number of rows for this cell.
In a future PR, we can consider syncing with the existing terminal, as well as edge validation cases.
> Introduce terminalRows annotation

- examples/README.md
- package.json
- src/client/components/configuration/annotations.ts
- src/extension/executors/runner.ts
- src/extension/executors/utils.ts
- src/extension/kernel.ts
- src/extension/provider/runmeTask.ts
- src/extension/runner.ts
- src/extension/utils.ts
- src/schema.ts
- tests/e2e/specs/basic.e2e.ts
- tests/extension/commands/index.test.ts
- tests/extension/executors/utils.test.ts
- tests/extension/kernel.test.ts
- tests/extension/messages/cellOutput.test.ts
- tests/extension/provider/annotations.test.ts
- tests/extension/runner.test.ts
- tests/extension/serializer.test.ts
- tests/extension/utils.test.ts
Allows running cells with custom languages. Provides new `program` cell annotation, with which the cell will run.
Requires runme with stateful/runme#302
Depends on #590
> Support custom cell executions

- package.json
- src/extension/api/client.ts
- src/extension/panels/panel.ts
- src/extension/services/runme.ts
- src/utils/configuration.ts
- tests/extension/configuration.test.ts
- tests/extension/panels/panel.test.ts
Plus additional safe-guards and tests.
Btw, merging this PR will effectively default every app user to production.
> Custom app config relies on base domains now

- src/extension/executors/runner.ts
- src/extension/provider/runmeTask.ts
Pass `languageId` down into the execution when present to avoid fallback behavior. "Mirrors" notebook execution.
Fixes: https://github.com/stateful/vscode-runme/issues/723
> Fix editor codelens execution for shebang

- package.json
To make it easier for users who want to use Runme but not for all markdown files everywhere.
> Add alternatives to *.md

- src/extension/executors/vercel.ts
- tests/extension/executors/vercel.test.ts
The Vercel deployment view would appear even if calling `npm i vercel`:
This patch fixes this error.
> (bugfix): fix Vercel deployment workflow

- .github/workflows/test.yml
- examples/test.md
- src/extension/executors/github.ts
- src/extension/executors/github/workflows.ts
- src/extension/extension.ts
- tests/e2e/pageobjects/cell.page.ts
- tests/e2e/specs/githubAction.e2e.ts
- webpack.config.ts
fixes #748
The test injects an environment variable to the global scope during test that helps to circumvent the GitHub authentication process. I made sure that this loophole is not available when compiling the extension in production.
> (test): add e2e test for github workflow usecase

- src/extension/executors/runner.ts
- src/extension/kernel.ts
- src/types.ts
Each time a new cell execution is triggered, if there is any existing executed integrated terminal, it should be removed and disposed, otherwise, it can create inconsistencies when referencing an active terminal by runme id.
We only need one single reference to the last active terminal per cell.
> Fix Terminal state

- src/extension/cell.ts
- src/utils/configuration.ts
I have introduced a side effect where passing in `null` into the Zod `safeParse` will fail return a default value. This patch fixes the problem.
> (fix): don't pass in 'null' when relying on defaults

- package.json
The default cursor width should be 1 instead of 0
> Fix cursor width for terminal

- assets/runme-logo-dark.svg
- assets/runme-logo-light.svg
- assets/runme-logo-open.svg
- package.json
move to a single runme logo for the title bar, 16x16, seems to properly inherit the right colors
> title bar icon upgrade

- src/extension/kernel.ts
- src/extension/runner.ts
- tests/e2e/specs/basic.e2e.ts
Unfortunately, since we have to adhere to the pseudo terminal interface, calling `dispose` on a terminal will cause a race condition where for a period of time it's unclear whether or not the underlying process has exited. Stopping an already exited process breaking every "second" successive runs of back-to-back runs of a cell.
https://github.com/stateful/vscode-runme/pull/829/files#diff-61fe624cda28319d214d5b79f135f89003df9be2b56ee99ddd05978827d9b40bR627
This PR introduces a timeout of 1s which only occurs when background tasks are being stopped. Since they are a lot less common and stopping them is infrequent it feels like the right tradeoff to me.
Steps to repro: run same cell (background=false) multiple times consecutively. Please note that `main` currently forgoes `dispose` to …
> Avoid race condition when dispose is called on terminals

- src/extension/kernel.ts
This is a follow-up to https://github.com/stateful/vscode-runme/pull/900.
After doing some research, it appears the best course of action is to only explicitly dispose resources Runme is actively creating to prevent negative side effects.
> Follow up fix to active terminal disposal race condition

- examples/shebang.md
- src/extension/executors/runner.ts
- src/extension/executors/task.ts
- src/extension/executors/utils.ts
- src/extension/provider/runmeTask.ts
- src/extension/utils.ts
- tests/extension/__snapshots__/utils.test.ts.snap
- tests/extension/executors/__snapshots__/utils.test.ts.snap
- tests/extension/executors/utils.test.ts
- tests/extension/utils.test.ts
Fixes https://github.com/stateful/runme/issues/418 by skipping shell/bash normalization for non-shell.
Completed an over-due refactor of the utility functions, which will avoid circular dependencies in dev.
Cc @edeediong. Once, https://github.com/stateful/runme/pull/419, ships we can remove `interpreter=php` from the shebang example.
> PHP shebang fix

- package-lock.json
- package.json
- src/extension/serializer.ts
- src/utils/configuration.ts
- tests/extension/configuration.test.ts
- tests/extension/serializer.test.ts
Depends on: https://github.com/stateful/runme/pull/416
The tests will fail until the proto changes are published to NPM. See trace below, this is expected.
```
ERROR in ./src/extension/serializer.ts:28:3
TS2305: Module '"./grpc/serializerTypes"' has no exported member 'RunmeIdentity'.
26 |   SerializeRequest,
27 |   Notebook,
> 28 |   RunmeIdentity,
|   ^^^^^^^^^^^^^
29 | } from './grpc/serializerTypes'
30 | import { initParserClient, ParserServiceClient } from './grpc/client'
31 | import Languages from './languages'
```
> Persist identity options in settings

- package.json
- src/constants.ts
- src/extension/cell.ts
- src/extension/commands/index.ts
- src/extension/extension.ts
- src/extension/provider/codelens.ts
- src/extension/runner.ts
- src/extension/serializer.ts
- src/extension/server/runmeServer.ts
- src/extension/utils.ts
- tests/extension/cell.test.ts
- tests/extension/extension.test.ts
- tests/extension/serializer.test.ts
- vitest.conf.ts
Unlocks https://github.com/stateful/runme/issues/400.
In this PR the outputs (when the experiment is active: `"runme.experiments.outputPersistence": true`) will be written to a session file that's derived from the original source document in the notebook. The UX offers a "Session Outputs" button (see below) that will conveniently open the outputs in a split view.
E.g.`./examples/README-01HGX7HZVNV4R74X1N1YKKDBK4.md` is based off `./examples/README.md`.
What's not covered yet:
1. The lifecycle of a session is currently the same as the VS Code window. However, in a future version, we could make a "New Session" button available to allow users to decide.
2. The "copy with outputs" can be opened as Runme notebook itself which does not make much sense. We could gracefully error in a future …
> Write separate session files for outputs

- .vscode/launch.json
- src/extension/cell.ts
- src/extension/constants.ts
- src/extension/kernel.ts
- src/extension/serializer.ts
- tests/extension/cell.test.ts
- tests/extension/serializer.test.ts
- vitest.conf.ts
The VS Code API provides limited control over serialization timing; however, this PR improves two things that were possible:
1. The session outputs file will be written on saving and serializing. The latter is new. This allows a near real-time (vscode debounces/throttles serialization, which introduces a slight lag) tracking of state side-by-side. This still feels more natural.
2. The notebook document is marked "dirty" (needs to be saved before closing/exiting) after every successful execution. This makes it explicit always to save when a "mutation" happens.
The changes feel natural and fix the problems described [here](https://github.com/stateful/runme/issues/400#issuecomment-1849030175) where serializing outputs to the session file do not match (out of sync) the latest notebook state …
> Improve serialization behavior/timing to avoid accidental data-loss

- src/extension/cell.ts
Without this change, the document won't be marked dirty after execution (which is incorrect).
Related to https://github.com/stateful/runme/pull/449.
> Cells with empty outputs but exec info (terminal state) are valid

- __mocks__/vscode.ts
- package-lock.json
- package.json
- src/extension/extension.ts
- src/extension/grpc/client.ts
- src/extension/grpc/projectTypes.ts
- src/extension/provider/codelens.ts
- src/extension/provider/launcher.ts
- src/extension/provider/runmeTask.ts
- src/extension/serializer.ts
- tests/extension/extension.test.ts
- tests/extension/runner.test.ts
Replace old/unfinished task provider integration with GRPC project service.
This is an intermediate step to make tasks more integral between "project mode" and VS Code's task system. What's missing but slated for follow up PRs:
To test this: Open the command palette and search for "Tasks: Run Task", select "runme" from the list. The list should match what you'd see (only named commands) if you run `runme ls` in the root of the repo. Select an entry to execute.
> Project service integration

- package-lock.json
- package.json
- src/extension/commands/index.ts
- src/extension/kernel.ts
- src/extension/serializer.ts
- tests/extension/commands/index.test.ts
- tests/extension/extension.test.ts
- tests/extension/kernel.test.ts
- tests/extension/serializer.test.ts
- vitest.conf.ts
This PR will introduce checks at the markdown/frontmatter level whether or not the document opened in the notebook UX was generated as a session outputs file. In the case of the latter, a modal will present alternatives. Please take a look at the screenshot below. This should be a sufficient solution until the deserialization of session outputs markdown is solved (if ever).
PS: A merge/release will require a new stable release of `runme` (including https://github.com/stateful/runme/pull/458).
> Deny session outputs (one-way serialization only; pending deserialization)

- CONTRIBUTING.md
- package.json
- src/extension/cell.ts
- src/extension/kernel.ts
- src/utils/configuration.ts
- tests/extension/cell.test.ts
- tests/extension/configuration.test.ts
Will count execution continuously across notebooks per session ID (starting new sessions will become available with Session Outputs currently opt-in). Skips "Configure" and non-cell executions.
> Set execution order according to session

- src/extension/provider/launcher.ts
- src/extension/provider/runmeTask.ts
- src/extension/utils.ts
- tests/extension/utils.test.ts
The project service will return absolute paths exclusively. However, in the UI we want them to be displayed relative to the workspace root(s) wherever possible. This PR introduces the baseline logic to do exactly that.
> Tasks relative display paths

- package-lock.json
- package.json
- tests/e2e/package-lock.json
- tests/e2e/package.json
This PR solves the Dependabot issue related to the **vscode-uri** module.
Closes: https://github.com/stateful/vscode-runme/issues/923
> wdio-vscode-service update to v5.2.2

- src/extension/survey.ts
Runme used to inform existing users about changes introduced in v2. Let's no longer auto-open the notification.
> Been long enough since v2

- .github/workflows/update.yml
This PR adds `skipped` as an allowed conclusions before executing the auto-merge. Needed because dependabot skips SonarCloud action.
> Add skipped to conclusions

- package.json
This is mainly for VS Code marketplace visibility.
PS: The keyword "runme" when the extension is called "runme" seems redundant.
> Introduce infra + cloud terminology

- package.json
- src/extension/commands/index.ts
- src/extension/extension.ts
- src/extension/utils.ts
- src/utils/configuration.ts
- tests/extension/extension.test.ts
Optionally letting users change the settings here seems a more straightforward way to handle where they don't want to be repeatedly asked to login.
> Use setting instead of globalState to disable login prompt

- CHANGELOG.md
- CONTRIBUTING.md
- examples/CATEGORIES.md
- examples/README.md
- examples/branchGPT.md
- examples/enhance/README.md
- examples/fresh/README.md
- examples/frontmatter/skipPrompts/DISABLED.md
- examples/frontmatter/skipPrompts/ENABLED.md
- examples/hardening/server.md
- examples/k8s/README.md
- examples/redis/query.md
- examples/shebang.md
- examples/test.md
- examples/vercel/README.md
- package.json
- src/client/components/configuration/annotations.ts
- src/utils/configuration.ts
- tests/e2e/specs/identity/identity.existent-cell.all.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.document.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.all.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.document.e2e.ts
- tests/e2e/specs/identity/identity.shebang.all.e2e.ts
- tests/e2e/specs/identity/identity.shebang.document.e2e.ts
1. Make SessionOutputs default `on`, note this will still not write them unless one toggles `Auto-Save (on)`.
2. Reformat markdown files to include new major-only version number.
3. Reshuffle annotation options to bring most important ones onto the `General` tab.
> Runme v3 release prep

- src/client/components/terminal/index.ts
- src/extension/kernel.ts
- src/extension/messages/platformRequest/saveCellExecution.ts
- src/extension/messages/platformRequest/updateCellExecution.ts
- tests/extension/kernel.test.ts
- tests/extension/messages/platformApiRequest/saveCellExecution.test.ts
- Remapped cloud API requests to platform API requests when platform authentication is enabled.
- Updated the response messages for saving cell executions to use platform API response messages.
- Added tests for platform API request handling and saving cell executions.
> Refactor platform API message handling in kernel.ts

- src/client/components/configuration/annotations.ts
- src/extension/extension.ts
- src/extension/provider/named.ts
- src/schema.ts
- tests/extension/extension.test.ts
- tests/extension/provider/named.test.ts
- tests/extension/utils.test.ts
Make it more clear that cells can have names: https://docs.runme.dev/configuration/cell-level#unnamed-vs-named-cells
Highlight that named cells are helpful to sift through lots of "cells".
While at it, fix https://github.com/stateful/runme/issues/490 and bring it into foldout.
https://github.com/stateful/vscode-runme/assets/250527/709c0810-22ce-4e80-95e8-d94832c08ae4
> Named cells UX in notebooks

- src/extension/utils.ts
Remove the error throw if there is no a Stateful session. This way the "EMPTY" string will be sent as a token to the webview panels app, so it can handle unauthenticated users.
> Remove throw if there is not a Stateful session

- __mocks__/vscode.ts
- src/extension/panels/panel.ts
- tests/extension/panels/panel.test.ts
Send VS Code `themeKind` as a field during the hydratation of the panels webview app.
> Send VS Code theme kind

- src/extension/provider/statefulAuth.ts
- src/utils/configuration.ts
These adjustments guarantee the correct operation of Stateful IDP on localhost. They involve the removal of mappings associated with specific subdomains linked to previous platform FQDNs.
> Restores functionality for Stateful IDP support on localhost

- __mocks__/vscode.ts
- package.json
- src/extension/provider/statefulAuth.ts
- src/utils/configuration.ts
- tests/extension/provider/statefulAuth.test.ts
Refactor the Stateful Identity Provider to remove the settings from the extension and delegate it to the API.
Things to do in the next iterations:
- Enhance the security between the extension and the Platform API,TLS Auth maybe...
- Increase the test coverage
> Refactor Stateful IDP to use Platform endpoints

- src/extension/provider/runmeTask.ts
Grab all emissions as a single array, then sort. As opposed to sorting every time a new emission shows up.
This fixes a significant slowdown in the extension host for repos with lots of markdown files.
> Avoid back pressure

- package.json
- walkthroughs/0-intro.md
Call them devops notebooks instead of infra to communicate broad utility
> Infra -> DevOps naming

- src/extension/executors/runner/index.ts
- tests/extension/executors/runner.test.ts
This refactor aligns with the requirement to eliminate custom business logic in the `vscode-runme` extension and utilize exclusively the returned values from the gRPC API provided by `runme`.
- Removed custom business logic from the `executeRunner` function.
- Updated the function to rely solely on the returned values from the gRPC API.
- Enhanced code readability and maintainability by restructuring the `executeRunner` function.
Closes: #1227
> Refactor executeRunner function in src/extension/executors/runner/index.ts

- src/extension/utils.ts
Introducing a fix to respect user selection when using auto-save feature.
Currently it uses the extension default when opening a Notebook, overwriting the user selection.
This PR fixes https://github.com/stateful/vscode-runme/issues/1235
> Keep auto-save user selection across notebooks

- examples/identity/existent-cell-id.md
- examples/identity/existent-doc-id.md
- examples/identity/shebang.md
- examples/shebang.md
- src/extension/panels/notebook.ts
- src/extension/serializer.ts
- tests/e2e/helpers/index.ts
- tests/e2e/specs/identity/identity.empty-file.none.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.all.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.cell.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.document.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.none.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.all.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.cell.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.document.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.none.e2e.ts
- tests/e2e/specs/identity/identity.shebang.all.e2e.ts
- tests/e2e/specs/identity/identity.shebang.cell.e2e.ts
- tests/e2e/specs/identity/identity.shebang.document.e2e.ts
- tests/e2e/specs/identity/identity.shebang.none.e2e.ts
The integration tests were to lenient to catch this bug (intro'd with refactor) since they only check for lifecycle identity presence.
Fixes #1251.
> Don't write cell IDs when turned off

- src/client/components/aws/ec2InstanceActions.ts
- src/client/components/aws/ec2InstanceDetails.ts
- src/client/components/aws/index.ts
- src/client/components/gcp/gke/cluster.ts
- src/extension/executors/aws.ts
- src/extension/executors/aws/ec2.ts
- src/types.ts
Add more consistency to cloud renderers, ensure information is accurate and all actions provide links to the original cloud resource when not available directly in the renderer.
This PR also polishes the styles and add more consistency with the current VS Code theme used by the user.
Some screenshots:
The AWS EC2 renderer now include better details:
The GCP styles has been polished:
> Polish AWS and GCP renderers

- src/extension/serializer.ts
- tests/extension/serializer.test.ts
Relaxes the requirement to have document-level lifecycle identity turned on to use the Session Outputs feature.
Solves https://github.com/stateful/vscode-runme/issues/1255.
> Use a cache ID versus lifecycle ID

- src/extension/utils.ts
- src/utils/configuration.ts
Use the most recently used strategy instead. This will allow existing terminals to transparently move sessions when the notebook does.
> Don't pin terminals to specific sessions

- examples/README.md
The second example won't actually run with `sh` versus `bash`.
> Use bash for both

- package.json
- src/utils/configuration.ts
- tests/extension/configuration.test.ts
The group of users who require this is much smaller than what makes sense for default now.
> Only require cell lifecycle identity by default

- src/extension/provider/codelens.ts
- src/utils/configuration.ts
- tests/extension/configuration.test.ts
Optionally add a new line when pasting from editor codelens into terminal.
This will skip an implicit "confirmation step" and run pasted command directly.
> Optionally new line when pasting from editor codelens

- src/extension/index.ts
Stateful Platform is a Superset of the Runme extension, so it is necessary to add a warning to avoid strange behaviour.
> Add a warning to avoid conflicts across Stateful extensions

- src/utils/configuration.ts
Fixes this issue where the kernel server is no longer running on an obsolete port.
```
could not execute command: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:7888: connect: connection refused"
```
Documented here: https://github.com/stateful/runme/issues/587#issuecomment-2130344799
> Make RUNME terminal ENV vars transient between restarts/reloads

- src/client/components/terminal/index.ts
- src/client/index.ts
- src/extension/cell.ts
- src/types.ts
Right now, the "Preview Gist" button appears even when session outputs are disabled, so to avoid confusion, this PR disables the button when the session outputs setting is off.
Closes: #1374
> Disable "Preview Gist" when session outputs are off

- package-lock.json
- package.json
- src/extension/executors/runner/index.ts
- src/extension/executors/task.ts
- src/extension/executors/utils.ts
- src/extension/grpc/client.ts
- src/extension/grpc/runner/types.ts
- src/extension/grpc/runner/v2alpha1.ts
- src/extension/provider/runmeTask.ts
- src/extension/runner/client.ts
- src/extension/runner/environment.ts
- src/extension/runner/index.ts
- src/extension/runner/program.ts
- src/utils/configuration.ts
- tests/extension/runner/runner.test.ts
Keep Runner v1 as default but allow v2 To allow for broader testing.
PS: C/I will fail until this PR's protos were published: https://github.com/stateful/runme/pull/589
> Runner with v1 <> v2 toggle

- src/extension/ai/generate.ts
* See jlewi/foyle#125 the language id isn't being set on cells inserted from Foyle
* As a result the language gets set to `text` and they aren't runnable.
> Fix Foyle language id on cells

- src/extension/panels/cloud.ts
- src/types.ts
Handle a new `onSiteOpen` event that the Cloud Panel app sends when a button should open Platform's site.
> Open Stateful site from panels.

- src/extension/__generated-platform__/gql.ts
- src/extension/__generated-platform__/graphql.ts
- src/extension/messages/platformRequest/saveCellExecution.ts
- src/extension/messages/platformRequest/updateCellExecution.ts
- src/gql-platform/createCellExecution.graphql
- src/gql-platform/updateCellExecution.graphql
Integrate the new field `isSlackReady` from the Platform API, so the Escalate button only shows up if the Slack's organization is already set up.
> Only show Escalate button if Slack is ready

- src/extension/utils.ts
- tests/extension/utils.test.ts
Catch the exception and stop cell execution as unsuccessful to prevent "runaway" execution as shown here:
https://github.com/stateful/vscode-runme/assets/250527/6e3dad27-bd40-4140-bade-22d98a866fc4
At some future point, I'd like to do a more substantial refactor of how Cloud Renderers are "embedded" in bash. However, we need to collect more feedback from usage first.
> Prevent notebook UX from being rendered unusable

- src/extension/ai/generate.ts
- src/extension/serializer.ts
- tests/e2e/helpers/index.ts
- tests/e2e/specs/identity/identity.shebang.all.e2e.ts
- tests/e2e/specs/identity/identity.shebang.cell.e2e.ts
- tests/e2e/specs/identity/identity.shebang.document.e2e.ts
- tests/e2e/specs/identity/identity.shebang.none.e2e.ts
- tests/extension/serializer.test.ts
- tests/fixtures/identity/shebang.md
Includes the following:
- Ports test suite updates (2a42f575fb3a4ff49ff670a81773b331182ee4be) from https://github.com/stateful/vscode-runme/pull/1359
- Removes reconcileCellIdentity (ran at serialization time; was a bandaid)
- Properly fixes the underlying issue by shifting it to deserialization time
Supersedes the bugfix in https://github.com/stateful/vscode-runme/pull/1359 and fixes https://github.com/stateful/vscode-runme/issues/1354 properly.
> Fix lifecycle ID for cells at deserialization time

- .github/scripts/overwrites/stateful.md
- src/extension/extension.ts
If no Platform Authentication exists on startup, a new stateful session will be created.
> Implements Stateful Platform Authentication on Startup 

- .github/workflows/release.yml
- .github/workflows/test.yml
Use native xvfb instead of `coactions/setup-xvfb@v1` because it's failing for GH pipelines. See  https://github.com/coactions/setup-xvfb/issues/19
> Use native xvfb

- src/constants.ts
- src/extension/serializer.ts
For example, `shell` is not a valid `languageID` in vscode-land. Cells will refuse to execute unless replaced with a valid value.
> Replace "unknown" languageIDs at deserialization

- .github/scripts/overwrites/stateful.sh
- __mocks__/vscode.ts
- src/extension/panels/cloud.ts
- src/utils/configuration.ts
- tests/extension/configuration.test.ts
- tests/extension/panels/panel.test.ts
This PR moves away from any panels served out of the legacy Runme cloud.
Let's plan for a follow-up effort to remove all non-platform panels/GQL since the backend is considered End Of Life.
> Start moving away from runme cloud domain/endpoint resolution

- src/client/components/terminal/index.ts
- src/client/index.ts
- src/extension/cell.ts
- src/types.ts
Hide the Preview Gist button when running the extension with Platform authentication.
> Hide preview gist button

- src/extension/provider/statefulAuth.ts
- tests/extension/provider/statefulAuth.test.ts
I believe the reason why we see "false positive" errors when switching stages is that auth tokens aren't valid across stages (staging, prod, etc). The solution is fairly simple by stashing the token into the secrets store under keys that are unique to the stages.
> Platform auth secrets per stage

- src/extension/serializer.ts
- src/extension/utils.ts
The deletion of the cell ID causes downstream issues. It also needs to be clarified why it was required in the first place.
I removed the logic to test it for a few days in pre-release.
> Simplify and remove deletion of cell ID

- package.json
- src/extension/utils.ts
- src/utils/configuration.ts
Solves https://github.com/stateful/runme/issues/639.
> Setting to let users decide if masked or unmasked should be default

- src/client/components/icons/eye.ts
- src/client/components/terminal/index.ts
- src/client/components/terminal/open.ts
Add an "Open" button when a cell output is saved. Clicking that button redirects the user to the Platform.
> Add open cell output button

- src/extension/messages/platformRequest/saveCellExecution.ts
- src/extension/utils.ts
- tests/extension/utils.test.ts
Use the forwarded `editor` instead of `window.activeTextEditor` to get the current file path of a git folder.
> Fix git dir

- dagger/Pipeline.md
- examples/dagger/Notebook.md
- src/client/components/dagger.ts
- src/extension/cell.ts
- src/extension/executors/dagger.ts
- src/extension/kernel.ts
- src/types.ts
This update introduces support for persisting the latest Dagger output. This ensures that the Dagger component’s state remains intact when interacting with cell outputs, such as adjusting settings, and preventing any potential loss of data or state during such interactions.
Closes: #1490
> POC to recover previous dagger state

- src/extension/ai/ghost.ts
Fix jlewi/foyle#188
The reason newly added ghost cells aren't executable is because they they lack a runme.dev/id metadata. This field gets set when cells are inserted but it was being removed by the code that updates the cell to set ghost to false. This updateMetadata calls was replacing the entire metadata with a new dictionary and not just updating it. So to fix it we need to pass in a dictionary that contains existing metadata that we want to preserve.
> Make ghost cells executable by preserving the runme.dev/id metadata

- .github/workflows/test.yml
- tests/e2e/specs/githubAction.e2e.ts
Excludes the end-to-end test that always fails due to permissions. Additionally, the auto-merge was disabled because we are doing it manually.
Having a CI passing ✅  helps to diagnose potential breaking changes in advance.
> Exclude GitHub Action e2e Tests for Dependabot PRs

- src/extension/executors/resource.ts
Since that's dangerous, let's not call `run` before wiring up the Promise is prone to a race condition
> Lucky that this race condition actually makes this work

- package.json
- src/client/components/configuration/annotations.ts
- src/client/components/configuration/categorySelector.ts
- src/client/index.ts
- src/extension/cell.ts
- src/extension/executors/aws.ts
- src/extension/executors/resource.ts
- src/extension/extension.ts
- src/extension/kernel.ts
- src/types.ts
- src/utils/configuration.ts
This PR introduces changes to make a best effort to determine if the shell is supported.
Progress: #1393
> Warn about unsupported shells

- src/extension/ai/manager.ts
- tests/extension/extension.test.ts
* We weren't actually reading the baseURL from the config because the key should be "aiBaseURL" not "runme.aiBaseURL"
* I tried to add logging to ensure we know what the actual value of the endpoint is but that seemed to prevent the extension from loading.
> Bug fix: AIManager doesn't properly get the configuration for baseURL

- .github/dependabot.yml
This change is necessary to let Dependabot update the package.json too.
> Change versioning-strategy to increase

- src/extension/ai/events.ts
- src/extension/kernel.ts
- tests/extension/kernel.test.ts
> Add tests to AI event logging

- tests/e2e/wdio.conf.ts
Tests are not working using the latest VS Code v1.93.0
```
connect ECONNREFUSED 127.0.0.1:61195
[0-5] RequestError in "Test suite: Empty file with setting All (1).should not remove the front matter with the identity"
RequestError: socket hang up
at ClientRequest.<anonymous> (file:///Users/cristian/Code/vscode-runme/tests/e2e/node_modules/got/dist/source/core/index.js:790:107)
at Object.onceWrapper (node:events:632:26)
at ClientRequest.emit (node:events:529:35)
at ClientRequest.emit (node:domain:489:12)
at Socket.socketOnEnd (node:_http_client:525:9)
at Socket.emit (node:events:529:35)
at Socket.emit (node:domain:489:12)
at endReadableNT (node:internal/streams/readable:1400:12)
at connResetException (node:internal/errors:720:14)
at Socket.socketOnEnd (node:_http_client:525:23)
at …
```
> Running e2e tests using VSCode v1.92.2

- package.json
- src/extension/provider/cellStatusBar/items/fork.ts
Shorter is better. While the ENV will be rolled up when exiting the session, we will add more terminal features shortly.
> Rename from "Fork ENV" to "Fork"

- src/extension/kernel.ts
This won't detach producer from consumer/reporter yet. However, it makes reporting more asynchronous, which is desirable.
> Await reporter after running the cell

- .github/scripts/overwrites/runme.md
- .github/scripts/overwrites/stateful.md
- .github/workflows/release.yml
> Rewire overwrites to use Runme GHA

- .github/dependabot.yml
Dependabot updates inside /examples/k8s are not significant, so these can have a separate scheduling.
> Separate dependabot rules for /examples/k8s

- package-lock.json
- package.json
- src/extension/commands/index.ts
- src/extension/kernel.ts
- tests/extension/commands/index.test.ts
It is likely broken due to the deprecation/changing of APIs. Require a minimum of VS Code v1.78.x now.
> Fix toggling between markdown/text with action buttons

- package.json
- src/extension/extension.ts
- src/extension/kernel.ts
- src/extension/server/kernelServer.ts
* This effectively reverts https://github.com/stateful/vscode-runme/pull/1380
* Per https://github.com/jlewi/foyle/issues/211 we are no longer relying on RunMe logs
* Rather RunMe now uses Foyle APIs to send events to Foyle as necessary.
> Remove option to enable aiLogs in the server

- src/extension/handler/uri.ts
- tests/extension/handler/uri.test.ts
This resolves the issue in code-server where a `Couldn't recognize command` error occurs during authentication against the Platform, because it expects the `windowId` URI parameter, which is missing.
The fix has been successfully tested in both code-server and standard VSCode environments.
> Fix code-server login

- package.json
- src/extension/extension.ts
- src/extension/utils.ts
- src/types.ts
The Runme extension loads the StatefulAuth provider, which could lead to a poor user experience. Even when the silent flag is passed, there is a listener that may activate the Badge in the User Menu, prompting a login suggestion.
In future PRs, when support for saving cells on the Platform is introduced, this flag can be enabled for Runme.
> Loads StatefulAuth provider only when it's necessary

- src/extension/commands/index.ts
- src/extension/extension.ts
- src/extension/kernel.ts
- src/extension/provider/cellStatusBar/notebook.ts
- src/extension/utils.ts
- tests/extension/commands/index.test.ts
Display a warning message and encourage users to switch to the `v2` (beta) version to take advantage of the feature.
This will make it more self-explanatory how to get started while still in beta.
> Turn on "Fork" button by default

- package.json
- src/client/components/terminal/index.ts
- src/client/index.ts
- src/constants.ts
- src/extension/cell.ts
- src/extension/commands/index.ts
- src/extension/executors/utils.ts
- src/extension/extension.ts
- src/extension/messages/platformRequest/saveCellExecution.ts
- src/extension/serializer.ts
- src/extension/utils.ts
- src/types.ts
- tests/extension/serializer.test.ts
Enables support to Save Cells in the Stateful Platform.
Updates the validation that skips writing session file, now it considers if auto-save is on/off to resolve it.
In Runme the Lifecycle ID is configured by default at Cell level, so the experiment **reporter** `(runme.experiments.reporter)` fails due to it needs the Frontmatter, which is not available. To solve this issue, this PR uses the Ephemeral ID as fallback.
- Dagger terminal outputs are not working with the Save button. I disable it for this kind of outputs.
> Enables Cells Saving in Runme

- CONTRIBUTING.md
- package-lock.json
- package.json
- src/extension/extension.ts
- tests/e2e/package-lock.json
- tests/e2e/package.json
- tests/e2e/specs/identity/identity.empty-file.all.e2e.ts
- tests/e2e/specs/identity/identity.empty-file.cell.e2e.ts
- tests/e2e/specs/identity/identity.empty-file.document.e2e.ts
- tests/e2e/specs/identity/identity.empty-file.none.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.all.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.cell.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.document.e2e.ts
- tests/e2e/specs/identity/identity.existent-cell.none.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.all.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.cell.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.document.e2e.ts
- tests/e2e/specs/identity/identity.existent-doc.none.e2e.ts
- tests/e2e/specs/identity/identity.shebang.all.e2e.ts
- tests/e2e/specs/identity/identity.shebang.cell.e2e.ts
- tests/e2e/specs/identity/identity.shebang.document.e2e.ts
- tests/e2e/specs/identity/identity.shebang.none.e2e.ts
- tests/e2e/wdio.conf.ts
- tests/extension/extension.test.ts
It seems that the command `> Developer: Reload Window` is generating a disconnection between the test runner and the chromedriver. This step is required to test Lifecycle Identity e2e Tests using different combinations of settings.
This PR refactors the Lifecycle ID e2e tests to avoid the usage of **Window Reloading** and enabled the latest version again.
Reverts stateful/vscode-runme#1622
Related: https://github.com/webdriverio-community/wdio-vscode-service/issues/136
> Going back to the latest stable VS Code version to perform e2e tests

- examples/k8s/package-lock.json
- package-lock.json
- package.json
Unified Dependabot updates. Typescript 5.6 was ignored in favor of patch versions.
> Dependabot 20241002

- src/extension/provider/cellStatusBar/items/cli.ts
- src/extension/provider/cellStatusBar/notebook.ts
- tests/extension/provider/notebook.test.ts
Per community request, the CLI Button comes back.
Special thanks to @forseti.
Closes: https://github.com/stateful/vscode-runme/issues/1692
> CLI Button comes back

- package.json
- src/client/components/terminal/index.ts
- src/types.ts
On Linux, the Notebook Terminal, it doesn't have the native capability to allow copy the selected text. Only works using the third mouse button to paste, I think this is a behavior of the X Server-Client.
This PR includes changes to allow copy to the clipboard using the most used keyboard shortcut, which is `SHIFT+CTRL+C`. It is designed to avoid conflicts with the `CTRL+C` (Terminate process).
> Add support to perform copy to clipboard on Linux

- src/extension/ai/ghost.ts
To support rendering markup cells as ghost cells we use the following hack
1. Insert the markup cells as code cells with languageId "markdown"
2. Replace the cells with a markup cell when the cell is accepted and ghost rendering is removed
To render ghost cells we rely on text decorations to change the font color to the grey color denoting ghost text. Text decorations only show up when a cell is in edit mode. Code cells get inserted in edit mode but markup cells are inserted in rendered mode. As a result the markup cells don't show up as ghost cells (jlewi/foyle#168). Unfortunately, there doesn't seem to be a public API that allows changing the cell mode to edit mode. It seems like putting the markup cell into edit mode requires changing the focus to that cell. I don't think we want to …
> Render markup cells as ghost cells

- package.json
- src/extension/extension.ts
- src/extension/messages/platformRequest/saveCellExecution.ts
- src/extension/serializer.ts
- src/utils/configuration.ts
- tests/extension/extension.test.ts
- tests/extension/fixtures/marshalNotebook.json
- tests/extension/serializer.test.ts
This means the default is to have neither cells nor document-level identity.
This PR requires https://github.com/stateful/runme/pull/677 and will now dynamically toggle lifecycle identity. It includes already opened docs that have passed the deserializer in the default off state.
PS: The document-level `runme.dev/id` was renamed to `runme.dev/cacheId` to be specific about its sole purpose.
> Make lifecycle identity truly optional in Runme

- src/extension/kernel.ts
- src/features.ts
- Loads settings before Feature-Flag instance.
- Avoids lower casing to have consistency in the Feature Names (convention).
> Fix Feature Flag runtime overrides

- src/extension/api/client.ts
- src/extension/features.ts
The user agent header is incorrectly set to `node-fetch/1.0 (+https://github.com/bitinn/node-fetch)`, instead of reflecting the actual VS Code platform.
New headers example:
> Adds additional headers to support better debugging in the cloud platform

- src/extension/messages/platformRequest/saveCellExecution.ts
- tests/extension/messages/platformApiRequest/saveCellExecution.test.ts
Instead of casting, explicitly throw an error if the notebook cache or the cell the user is trying to save is not found.
> Explicit errors when saving cells 

- src/extension/ai/manager.ts
- src/extension/ai/sessions.ts
* Use the status bar to display the session id
* The session id is used to track all the AI generations associated with a particular context
* Surfacing the session id makes it easy to fetch the relevant Foyle logs to understand why the AI made a particular suggestion.
Fix: jlewi/foyle#322
> Add a Foyle status bar in the lower right corner

- .github/dependabot.yml
- package-lock.json
- package.json
Pins the module `@types/node` to the v20.x in order to be consistent with the Node version.
> Dependabot config to pin `@types/node` to `v20`

- src/extension/ai/events.ts
- src/extension/ai/manager.ts
- src/extension/kernel.ts
Use subject (special observable) to separate the producer from the consumer to keep the producer path unblocked.
> Non-blocking event reporting

- package.json
- src/extension/extension.ts
- src/extension/features/addTrustedDomains.ts
- src/extension/features/autoOpenTerminal.ts
- src/extension/features/index.ts
- src/types.ts
- tests/extension/features.test.ts
Introduces changes to enhance the user experience when running hosted extension within Stateful Cloud Playgrounds.
* Configure trusted domains.
* Auto open a new terminal only the first time.
> Improves user experience inside Stateful Cloud Playgrounds

- src/extension/__generated-platform__/gql.ts
- src/extension/__generated-platform__/graphql.ts
- src/extension/kernel.ts
- src/extension/messages/platformRequest/index.ts
- src/extension/messages/platformRequest/saveCellExecution.ts
- src/extension/messages/platformRequest/trackRunmeEvent.ts
- src/extension/serializer.ts
- src/gql-platform/trackRunmeEvent.graphql
- src/types.ts
- tests/extension/kernel.test.ts
- Track runme cell run events and save it to the Cloud database only when the user is logged in.
- Some type narrowing clean up to avoid casting
Depends on https://github.com/stateful/platform/pull/1213
> Track Runme runs (logged into Stateful-only)

- src/extension/kernel.ts
- src/extension/signedIn.ts
- tests/extension/kernel.test.ts
1. Break out code that only runs for logged in users
2. Enqueue cell runs (sync), immediately return to unblock execution
3. Report cell runs only for logged in users (async)
> Fully async to never block execution

- src/extension/messages/platformRequest/saveCellExecution.ts
The Cloud Panel was being opened automatically for auto-saving, which is unnecessary. This change ensures it only opens when explicitly required.
> Open Cloud Panel only when the Save button is clicked

- examples/aws/ec2.md
- src/client/components/aws/ec2Helper.ts
- src/extension/messages/aws.ts
- tests/client/components/aws/ec2Helper.test.ts
- Expanded supported patterns to include rhel and suse-sles images.
- Introduced a defaultUserName (ec2-user) for unsupported or unmatched image patterns.
- Updated resolveOsUserName function to handle null or undefined values for imageName.
- Fixed case-sensitivity issues by converting imageName to lowercase before matching.
- Simplified logic to ensure robust and predictable username resolution.
- Included the **--region** flag
Closes: #1807
> Improve OS username resolution for EC2 instances

- src/extension/executors/runner/index.ts
- tests/extension/executors/runner.test.ts
Fixes https://github.com/stateful/runme/issues/710.
Moving to `runnerv2`, we should move all normalization into the `ProgramResolve` API.
> Exclude heredoc from normalization

- src/client/components/configuration/annotations.ts
- src/extension/cell.ts
- src/extension/executors/runner/index.ts
- src/extension/executors/task.ts
- src/extension/provider/background.ts
- src/extension/runner/index.ts
- src/schema.ts
- src/types.ts
- src/utils/configuration.ts
- tests/extension/provider/annotations.test.ts
- tests/extension/provider/background.test.ts
- tests/extension/provider/notebook.test.ts
- tests/extension/provider/sessionOutputs.test.ts
- tests/extension/schema.test.ts
- tests/extension/utils.test.ts
As @jlewi summarized in https://github.com/stateful/runme/issues/684:
> * Interactive terminals multiplex stdout and stderr and show the multiplexed stream in the Cell output window
> * non-interactive terminals don't multiplex stdout/stderr and only stdout is sent to the cell output window
> * non-interactive terminals don't multiple stdout & stderr because this could interfere with 3rd party renders
>   
>   * For example imagine a CLI is emitting a JSON table to stdout and also sending errors to stderr
>   * If you multiple stdout & stderr you no longer have a stream of valid JSON
>   * So a 3rd party renderer for JSON would break if you multiplexed stdout and stderr
> * So the proposed fix for non-interactive terminals is to send stderr to the vscode integrated terminal in the bottom …
> Rewire stdio for non-interactive

- src/extension/ai/ghost.ts
* The bug is described in https://github.com/jlewi/foyle/issues/316
* The problem was we weren't deleting the previous ghost cells until we were ready to insert the new ghost cells. When we deleted the ghost cells this could shift the current cells up. This could lead to the active cell shifting up and losing focus. This was very confusing. It felt like the ground was changing underneath you.
* This PR fixes that by deleting the ghost cells from the current compeltion as soon as you change the cell focus to a new cell. Therefore by the time you start typing the previous ghost cells have already been removed.
* I think this is a much better experience.
* I think the original UX was motivated in part to give you time to look at the previous ghost cells while you are still typing. I also …
> Prevent ghost cells from changing cell focus

- src/extension/executors/runner/index.ts
- src/extension/terminal/terminalState.ts
Serialize the full cell output content when saving a notebook. This is needed because XTerm serialization only returns the content that's visible in the terminal, causing the cell outputs to be saved with "incomplete" content.
> Cut off outputs

- src/constants.ts
- src/extension/extension.ts
- src/extension/handler/uri.ts
- src/extension/handler/utils.ts
- src/extension/utils.ts
The difference is:
```
README.md
```
versus
```
README.md#1
```
Where `1` is the second code cell in the `README.md` notebook.
> Optionally focus a cell when using bootstrapping

- .github/workflows/test.yml
- tests/e2e/specs/githubAction.e2e.ts
This E2E test requires organization-level access and can only be properly verified by organization members or after a PR is merged into the main branch.
To streamline the workflow and avoid unnecessary failures, this test is now disabled for forked repositories, similar to how Dependabot PRs are handled.
> Skip GitHub E2E Tests for Forked Repositories

- package.json
- src/extension/extension.ts
- tests/extension/extension.test.ts
This update introduces the runme.authenticateWithStateful command, enabling authentication independently of the Cloud Panel.
Previously, users could not authenticate when the Cloud Panel was unavailable. This command resolves that limitation, providing a direct way to authenticate with Stateful.
> Added Command: `runme.authenticateWithStateful`

- src/extension/provider/runmeTask.ts
Just some small things:
1. Use rx observables throughout.
2. Sort lexically on the same dir level.
> Review feedback

- package.json
- src/extension/extension.ts
- src/extension/provider/launcher.ts
- src/extension/provider/launcherBeta.ts
- src/extension/provider/runmeTask.ts
The new launcher doesn't have a way to synchronize new, updated, or removed cells/notebooks. For now, this PR introduces a button to manually update the content of the panel. However, in a next iteration, a file system watcher would be considered.
> Adds support to manually refresh launcher

- src/extension/serializer.ts
- tests/extension/serializer.test.ts
This change is required since Web gRPC, unlike TCP gRPC, returns `Buffer` and not `Uint8Array` as Buffer data type.
Required to release https://github.com/stateful/vscode-runme/pull/1876.
> Use Buffer instead of Uint8Array

- src/extension/cell.ts
- src/extension/commands/index.ts
- src/extension/extension.ts
- src/extension/kernel.ts
- src/extension/messages/github.ts
- src/extension/messages/platformRequest/saveCellExecution.ts
- src/extension/serializer.ts
- src/extension/signedIn.ts
- tests/extension/serializer.test.ts
The NotebookData structure doesn't include transient metadata, but I need the cell ID to properly track terminal outputs.
I extract the cell ID from the terminal output metadata, which is always available when the cell has a terminal output. This is a more reliable way to get the cell ID
This is particularly problematic when lifecycleIdentity is NONE since cells won't have IDs assigned directly.
Closes: stateful/runme#728
> Fix Preview Outputs when Life Cycle Id is disabled

- src/extension/provider/runmeFs.ts
The GraphQL API returns the decoded data, so we don't need to decode it again.
Depends on: stateful/platform#1296
> Remove unnecessary decoding of base64 data

- src/extension/cell.ts
- src/extension/executors/runner/index.ts
- src/extension/kernel.ts
- src/extension/runner/index.ts
- src/extension/terminal/terminalState.ts
- src/ringBuffer.ts
- src/utils/configuration.ts
- tests/e2e/helpers/index.ts
- tests/ringBuffer.test.ts
Ever-growing buffers are dangerous for memory consumption and downstream API limits. To avoid running into API payload limits, use `scrollback` settings as a buffer limit.
I have encountered issues when a chatty background process runs inside a notebook terminal. After a while, it will experience both remote and kernel API size limitations.
Using the `scrollback` setting will put control into a user's hands.
> Use RingBuffer to prevent ever-growing buffer

- package.json
- src/extension/executors/utils.ts
- src/extension/extension.ts
- src/extension/provider/runmeFs.ts
Workspace folders now serve as the current working directory for remote notebooks. This is necessary for shebang cell runs.
When no workspace is detected, it defaults to using a temporary directory.
> Use workspace folders as cwd for remote notebooks

- __mocks__/vscode.ts
- src/extension/messages/platformRequest/saveCellExecution.ts
- src/extension/provider/statefulAuth.ts
- src/utils/promiseFromEvent.ts
This update ensures that users must complete the authentication process before saving a cell. It improves reliability by handling authentication state transitions seamlessly during cell run, enhancing the user experience.
It now makes its best effort to wait for the user to complete the happy path, keeping the save button in a loading state. If authentication is completed within a minute, the cell is saved automatically without requiring the user to press save again. If authentication fails, the user is notified, and the save button returns to its initial state.
https://github.com/user-attachments/assets/fe879d71-28d3-4b29-83e0-2252ec1bd6f7
> Wait for authentication to complete before you can save a cell

- .github/dependabot.yml
Updates ignore entries and includes **expect-webdriverio** in the e2e-tests group.
> Updates dependabot config

- src/extension/executors/runner/index.ts
- src/extension/terminal/terminalState.ts
We're coming full circle here. While the `RingBuffer` worked well to manage capacity, it lacks the interpretation of TUI-like ANSI sequences. TUIs ncurses-like UIs that aren't just growing text output, they use the screen more like a canvas.
This PR handles TUIs better (still needs to capture notebook terminal dimensions), especially when saved as Gist or into the Cloud.
Compare https://gist.github.com/sourishkrout/dbc9037bce8fcf17ba283db939ddc804 (no term emu) vs https://gist.github.com/sourishkrout/7d382f162313d01cc9b1ae0120d93e49 (with term emu).
> ANSI sequences need to be interpreted for TUIs

- src/extension/extension.ts
- src/extension/kernel.ts
- src/extension/runner/index.ts
- tests/e2e/specs/codelense.e2e.ts
- tests/extension/runner/runner.test.ts
This mimics what we do in the notebook and makes the terminal output more readable. Especially if both `stdout` and `stderr` are interspersed.
The difference is **with buffering**:
Before the change **without buffering**:
Example cell (`interactive: false`): https://gist.github.com/sourishkrout/d61c3226473afdc030951bdc167d15cd#file-01jkvp47gcjh2s6mgysf16j06b-md
> Buffering for non-tty output (non-interactive) in the vscode-integrated terminal

- .github/workflows/release.yml
This pull request includes a minor update to the `.github/workflows/release.yml` file. The update adds a condition to ensure that the deactivate-panels workflow only runs if the releaseChannel is not set to 'edge'.
This change is necessary to enable and test the Cloud Search and Chat features within the Edge Release channel.
> Disable deactivate-panels workflow for edge releases

- src/extension/signedIn.ts
- tests/extension/signedin.test.ts
This pull request includes changes to the `SignedIn` class in `src/extension/signedIn.ts` to improve code accessibility and adds new tests for the `SignedIn` class in `tests/extension/signedin.test.ts`.
Closes: #1933
> Add tests for SignedIn operations

- src/extension/kernel.ts
- tests/extension/kernel.test.ts
This introduces a new option to run all cells sequentially and in parallel based on the user's preference.
Solves https://github.com/stateful/runme/issues/737.
> Allowing runing all cells in parallel

- src/extension/executors/utils.ts
- tests/extension/executors/utils.test.ts
The idea is for the `program` (shell or not) to overwrite from macro to micro, where the latter wins in order:
1. `shell` in frontmatter
2. `interpreter` on individual cell(s)
3. system shell as default for shell-ish, others inferred from languageID (inside kernel)
This PR fixes a scenario where `shell: dagger shell` in frontmatter wouldn't allow an interpreter to be set on cells. It also consolidates the code to be more concise.
> Interpreter (cell) beats frontmatter's shell

- package-lock.json
- package.json
- src/extension/runner/index.ts
- src/utils/configuration.ts
This setting remains disabled by default disabled during a soft rollout.
> Setting for direnv that's default disabled

- src/extension/utils.ts
If the cell has interpreter set, use it over frontmatter. If it's not `dagger shell` don't use Dagger Shell.
> Disabled Dagger UX for cell interpreters that are non-dagger

- .env.spec
- .envrc
- dagger.json
- dagger/notebook/shell.dag
- dagger/package-lock.json
- dagger/src/index.ts
- examples/aws/ec2.md
- examples/aws/eks.md
- examples/dagger/Notebook.md
Make building Runme extensions a no-brainer.
> Link Runme and RunmeVscode Dagger modules

- .prettierignore
- BUILD.md
- CONTRIBUTING.md
- dagger/BUILD.md
- dagger/scripts/presetup.sh
- dagger/src/index.ts
- tests/e2e/wdio.conf.ts
This PR makes `runme run UnitTests` & `runme run IntegrationTests` available. The latter will only work on a Linux system that's capable of running virtual X frame buffer (aka `xvfb`).
Once this is merged, we'll start on migrating CI/CD to it.
> Daggerize testing including e2e integration tests

- dagger/BUILD.md
- dagger/src/index.ts
- tests/e2e/wdio.conf.ts
Make it possible to run tests against a complete build or prebuilds downloaded from GitHub.
> Expand Dagger module to include pre-built extensions

- package-lock.json
- package.json
- tests/e2e/package-lock.json
- tests/e2e/package.json
- tests/e2e/wdio.conf.ts
The upstream library was merged and released https://github.com/webdriverio-community/wdio-vscode-service/pull/150
> Run e2e tests against a newer vscode version (not stable yet)
